### PR TITLE
Add method select row, single and column

### PR DESCRIPTION
**Pull request by felipehertzer**
Added method select only one row, only field, and column from a datebase and added method prepare sql.

Added fetch and fetchColumn.

### CODE REVIEW

**Comment by jimgwhit** [comment]
You can get one record already:
```
public function getPet($petid)
    {
        return $this->db->select("SELECT * FROM " . PREFIX . "pets WHERE petid =:petid", 
         array('petid' => $petid));
    }
```
and binding is taking place already: for example:
```
public function insert($table, $data)
    {
        ksort($data);

        $fieldNames = implode(',', array_keys($data));
        $fieldValues = ':' . implode(', :', array_keys($data));

        $stmt = $this->prepare("INSERT INTO $table ($fieldNames) VALUES ($fieldValues)");<---here

        foreach ($data as $key => $value) {
            $stmt-> bindValue(":$key", $value);<-----------------------here------------
        }

        $stmt->execute();
        return $this->lastInsertId();
    }
```
and
```
public function select($sql, $array = array(), $fetchMode = PDO::FETCH_OBJ, $class = '')
    {
        $stmt = $this-> here here here prepare($sql);<--------here-----------------------------
        foreach ($array as $key => $value) {
            if (is_int($value)) {
                $stmt->bindValue("$key", $value, PDO::PARAM_INT);<-------here-----------------
            } else {
                $stmt->bindValue("$key", $value);<------------here------------------------
            }
        }

        $stmt->execute();

        if ($fetchMode === PDO::FETCH_CLASS) {
            return $stmt->fetchAll($fetchMode, $class);
        } else {
            return $stmt->fetchAll($fetchMode);
        }
    }
```
I feel the database helper is fine as is.

**Comment by geomorillo** [comment]
Yes this is already implemented in helper

**Comment by jimgwhit** [comment]
@volter9 how about some input here.

**Comment by jimgwhit** [comment]
Or aa single field
~~~
public function getPet($petid)
    {
        return $this->db->select("SELECT petname FROM " . PREFIX . "pets WHERE petid =:petid", 
         array('petid' => $petid));
    }
~~~

**Comment by geomorillo** [comment]
You can get any field and any record, just implement it n your own model

**Comment by daveismyname** [comment]
I agree with the others the class does everything it needs to do I don't see that adding anything needed, as @geomorillo suggested you can alter your methods within your helper/view.

**Comment by volter9** [comment]
@jimgwhit I think I'm late to share with my thoughts. :cry: 

Although, I think that `raw` should have return statement before it, so people could use returned `PDOStatement` for fetching custom result, etc.

**Comment by daveismyname** [comment]
just to be clear is this what you mean:

````
$data = $this->query($sql);
return $data->fetchAll(PDO::FETCH_OBJ);
````

**Comment by volter9** [comment]
@daveismyname yeah, something like that.

**Comment by daveismyname** [comment]
ah that code results in an error just a simple return does the job.

````
return $this->query($sql);
````

I'll update the class.

**Comment by volter9** [comment]
@daveismyname thanks! :+1:

**Pull request closed without merging**
