### PR TITLE
SQLite Service

### PR DESCRIPTION
**Pull request by tomvlk**
Ready :+1: .
You can merge.

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk If there is need for **app/Models/Entities/CarLite.php** something is very very very wrong in your implementation, like a black entering in a skin-heads dedicated Club...

**Comment by tomvlk** [comment]
It's because the 2 test cases are different. And I will fix that in another pull request later. That will make the database demo better.

**Comment by LuckyCyborg** [comment]
@tomvlk How about to fix now, on this PR?

The Application Services shall be agnostic about the Database Engine, or I miss something about your vision?

**Comment by LuckyCyborg** [comment]
@ And, you use directly **Nova\Database\Service\SQLite** in a Application Service? Amazing! :sake:

**Comment by tomvlk** [comment]
Ongoing development. It's not fully done yet as I tried to tell you before. Other changes are coming in another pull.

**Comment by LuckyCyborg** [comment]
@tomvlk My friend, Tom...

We, us, we have at disposition now, just **six** days to complete the development on this Project, for a **usable** stage. That's including the **Santa Claus Day**. And on **24**, today, we have to make a presentation about our stage on this Project.

There is no room for **ongoing development**. We need, fast, a feature complete **DBAL**, or **no problem!** you can pass us the Flag and we continue us from there. Quickly.

In a way or another our Project should be functional on New Year... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk After frugally studying your code, I arrived to conclusion that your Services are still in a **Demonstrative Stage**, and they aren't ready for **Factorized/Mult-Engine Stage**. While the idea, as is, is beautiful, there is still huge room for development and it very clear that the Database Services part is not ready to be included in a first functional release of Nova Framework, expected by us as being Release Candidate at end of this Year, expected by Dave to be Release at the end of January.

I will open an Issue and I will propose myself a patch to get ridding of the Database Services, as being **NOT** Design ready for an appropriate Release.

I hope the other members of SMVC community will understand my position and I will gain support on.

Then, let's be honest! I propose you to nuke all support for Database's Services, including the collateral  one; and to continue the development of **DBAL**, then, in future, when you are ready with a solution for Database's Services, to push them again into Framework.

Looking at your **DBAL**, I believe to arrive to a functional state in very short time, I hinted just some Design problems which need to be fixed, so this is the best option for all us. Eventually we will start to fix them ourselves.

Finally, let's see the Bright Side: You made a really beautiful Database Engine! It's not the end of World if those Database Services will be ready for **SMVC 4.0**! Be man! :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg wow. This. Wtf. You are a bit ego here. 
Let's be clear here. This is a project by DAVE. And not by you I think. 
And you have a deadline. But it's only you right?

Some people need to calm down. You just don't want this in it right? But again it's only you. 
And why isn't it ready exactly? Because I think that it needs small improvements and an updated demo....

Anyway. Going to ignore you right now. You try to push your opinion into others..

**Comment by tomvlk** [comment]
And about the multi engine support. That will be fixed in next pull today with drastic design changes of the services. (DBAL)

**Comment by LuckyCyborg** [comment]
@tomvlk 

### Finally, looks like that ll you need is to merge **\Nova\Database\Service\MySQL** into **\Nova\Database\Service** and that's all Folks! Then you can start the cleanup and optimization.

You really don't need specialization from this pull-request, in opinion. 

And, I do not try to push my opinion into others, my dear friend! Sorry for you to understand that!

Worry not, I understand well that our POV are very different from one of us.

For you, this **SMVC3/Nova** is for fun, a field for experiments, for me, it is one of job tasks, with, like you said, a deadline to finish the implementation. 

Yet, my deadline do not say that Dave shall do a Release on New Year, it simply say to rise this Design to an **Usable State**. As in, this Design to be stable (and complete) enough to permit us to start building things on top of it. 

When I first arrived there, I said very clear: **we want to improve SMVC**, use it on some of our Projects and we have no intention to do internal or public forks. Still, you do not suspected that when a Company wants something, there are also deadlines? Sorry for that!

Finally, don't worry, no one of us want to push something in your Design or whatever. It is also funny situation:

US: We should give you, dear SMVC Community, a shinny new&improved Framework before the current Year end!
YOU: Whaaa! OMG! You guys started to push your opinion into others!

**Comment by tomvlk** [comment]
@LuckyCyborg the framework is fun to me because I use it in several big projects ;).
I will open pull request for making it more multi-engine supportive!

**Comment by tomvlk** [comment]
@LuckyCyborg I understand what you ment, and you were right on the structure, look at the nice #300 request that will implement just ONE service you should extend on your services.
Tonight I will add an interactive demo with php code and result on the demo pages. Also add demo config, exports for database so it could be easely tested.

**Comment by LuckyCyborg** [comment]
@tomvlk And that Design of your Services implementation looks spectacular better! Congratulation!

**Pull request closed without merging**
