### PR TITLE
Adding the \Smvc\Helpers\Validator class, who validate input arrays; …

### PR DESCRIPTION
**Pull request by LuckyCyborg**
…also it's based on our ol'good friend GUMP.

Example Usage:

```php
        $config = array(
            'username' => array(
                'label'  => __d('user', 'User Name'),
                'rules'  => 'required|unique_username|valid_name|max_len,30|min_len,5',
                'filter' => 'trim|sanitize_string'
            ),
            'password' => array(
                'label'  => __d('user', 'Password'),
                'rules'  => 'required|strong_password',
                'filter' => 'trim'
            ),
            'confirm_password' => array(
                'label'  => __d('user', 'Confirm  Password'),
                'rules'  => 'required|equalsfield,password',
                'filter' => 'trim'
            ),
            'firstname' => array(
                'label'  => __d('user', 'First Name'),
                'rules'  => 'required|valid_name|max_len,30|min_len,5',
                'filter' => 'trim|sanitize_string'
            ),
            'lastname' => array(
                'label'  => __d('user', 'Last Name'),
                'rules'  => 'required|valid_name|max_len,30|min_len,5',
                'filter' => 'trim|sanitize_string'
            ),
            'email' => array(
                'label'  => __d('user', 'E-mail'),
                'rules'  => 'required|valid_email',
                'filter' => 'trim|sanitize_email'
            ),
            'userlevel' => array(
                'label'  => __d('user', 'User Level'),
                'rules'  => 'integer|max_numeric,255|min_numeric,0',
                'filter' => 'trim|sanitize_numbers'
            ),
        );

        if(Request::isPost()) {
            if (! Csrf::isTokenValid()) {
                Url::redirect('login');
            }

            $validator = new Validator($config);

            //
            $postData = $validator->run($_POST);

            // Check if validation was successful
            if($postData !== false) { 
                //blah, blah, blah
            }
            else {
                $userinfo = $validator->getData();

                $error[] = $validator->getErrors();
            }
       }
``'

### CODE REVIEW

**Comment by geomorillo** [comment]
sorry whats this  __d(   did i mis something?

**Comment by LuckyCyborg** [comment]
@geomorillo Hi, my Spanish friend!

The functions **__()** and **__d()** are two functions who return the translated strings. The second one use a Language Domain, in this case being "system".

BTW, will be very nice to look at System's new translation strings for Spanish!

**Comment by geomorillo** [comment]
i see since i never used them...

**Comment by LuckyCyborg** [comment]
@geomorillo Sure you never used them!

Those functions are part of **Internationalization Engine** written by us for SMVC3, or, I should say, the new **Nova Framework**.

**Pull request merged**
