### PR TITLE
3.0 - Final Phase, stage continued #35

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Improve **\App\Core\BaseModel**

### CODE REVIEW

**Comment by tomvlk** [comment]
Nice work again. It would be great to have some more phpdoc blocks when we are finished at the end. Will help most ide's with autocompletion and type help 
Also easy for phpdoc pages (generate html)

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks!

Also, well, the documentation part is not my strongest skill. :smile:

And, I not English native, like you seen. I'm afraid that I speak some "Engrish" there... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg I think some of us will help :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks, and there, on Documentation, is right on the case to have some community help... :smirk:

BTW, now **BaseModel** know **how to validate** the Data for (some of) its methods. 

Of course, shameful using **\Nova\Helpers\Validator**

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, you like the little Query Builder who come into **BaseModel** ?

Sure, this Base Model is not intended to be a real QueryBuilder, rather is oriented to usual CRUD operations, but, considering that we not have a QueryBuilder into Database & Co., was required to introduce some simple&usual Builder commands there...

**Comment by tomvlk** [comment]
@LuckyCyborg Ye saw it, really nice!

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks!

But, if come to need **JOIN**s, the end-user is in its own... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk You know what our Engines lack? 

An **escape()** method... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg To escape from the universe? :laughing: :rocket: :trollface:

**Comment by LuckyCyborg** [comment]
@tomvlk Yep! :+1: 

Or, more ground minded, to custom escape/quote the things. Useful when you go hard way, via RQW QUERIES... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg And then use the PDO quote method? That would be fine I think, but we need to doc that with no responsibilities. Better use is the prepare and bind of course.

**Comment by LuckyCyborg** [comment]
@tomvlk Sure thing that should be not recommended this way! :smirk: 

But, as I said, an 'escape' method is handily and simple to implement on top of PDO quote...

**Comment by tomvlk** [comment]
@LuckyCyborg Going to implement that today or maybe next year :laughing: .

**Comment by LuckyCyborg** [comment]
@tomvlk And if we talk about the best way to process the Data from Users, the best is to do a **Validation** (and **Filtering**), first... :smirk: 

You know the saying: The Users do naughty things. Always.

**Comment by tomvlk** [comment]
@LuckyCyborg :+1: :laughing:

**Pull request merged**
