### PR TITLE
Adding add to Config class. To add values to a config value array.

### PR DESCRIPTION
**Pull request by tomvlk**
Just as the title say.
You can add values to an existing config value (array value).
This will allow modules to add a database link to the database config.

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk Goog Job, Tom! :+1: 

I susscribe to your propose! :smile: 

This time, you literally read my mind, this \Nova\Config::add was discussed at our Briefing as being necessary, i.e. for the Modules adding of Menu Items elements, or even in your scope, to extend the Database configuration.

Also, I see it being well guarded on errors. :+1:

**Comment by tomvlk** [comment]
@LuckyCyborg Maybe I was there too :trollface: 
I missed it when I wanted to start on the demo stuff ;)

**Comment by LuckyCyborg** [comment]
@tomvlk also, **Houston, we have a problem!**

You Services aren't **Modules aware**. We should talk about that problem and you should take action...

**Comment by tomvlk** [comment]
@LuckyCyborg Look at the next pull request :trollface:

**Pull request merged**
