### PR TITLE
Deleted some unused variables

### PR DESCRIPTION
**Pull request by geomorillo**
$data and $error was unused, also addHeaders was edited.

### CODE REVIEW

**Comment by daveismyname** [comment]
they are used just not in the method directly, for instance the $data is used inside the views the view::render method includes, without $data the controller cannot pass any information to the view.

**Comment by geomorillo** [comment]
Oh i see my bad i must be on drugs right now lol i forgot those variables.

**Comment by daveismyname** [comment]
haha no worries :)

**Comment by geomorillo** [comment]
please close this

**Pull request closed without merging**
