### PR TITLE
Revert "3.0 - Several fixes in Nova DBAL"

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Reverts simple-mvc-framework/framework#442

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
What you do not understand that you cannot rely into this numeric keys?

Look there:

```php
        // Bind fields
        $this->bindParams($stmt, $data, $paramTypes, ':field_');

        // Bind values
        $this->bindParams($stmt, $bindParams, $paramTypes);
```

**Comment by tomvlk** [comment]
@LuckyCyborg Please don't just force it! You should really consider talking a bit more and maybe understand it.

**Comment by tomvlk** [comment]
@LuckyCyborg Query builder can! Because you prepare it and it will be numeric all the time!

**Comment by LuckyCyborg** [comment]
@tomvlk Then use directly the QueryBuilder and do not touch the **Connection** introducing strange bugs!

**Comment by tomvlk** [comment]
@LuckyCyborg Please stop the childish Adrian here.

**Comment by LuckyCyborg** [comment]
@tomvlk I'm not childish. Look into code and you will see that the **bindParam** should be index safe to use numeric bindings.

Because it can be called several times in a single method.

**Comment by tomvlk** [comment]
@LuckyCyborg Ok, please make it so you can use question mark bindings!

**Comment by tomvlk** [comment]
@LuckyCyborg But not revert right now.

**Pull request closed without merging**
