### PR TITLE
Adjusted invokeObject method in router for PHP7

### PR DESCRIPTION
**Pull request by volter9**
Thanks to @jimgwhit for testing the code on PHP7 :smiley:

### CODE REVIEW

**Comment by jimgwhit** [comment]
@volter9  where is your framework branch?

**Comment by jimgwhit** [comment]
Dave, once this is pushed, framework works on php 7 back to php 5.4 as is.  But by all means test out error handling.  The new throwable interface really made things easier.

**Comment by volter9** [comment]
> @volter9 where is your framework branch?

I didn't really get what you mean. I requested pull requested from master to master.

**Comment by jimgwhit** [comment]
You don't have an online branch?

**Comment by volter9** [comment]
What is an online branch?

**Comment by jimgwhit** [comment]
I meant fork

**Comment by volter9** [comment]
That's my fork:
https://github.com/volter9/framework-1

**Comment by daveismyname** [comment]
Massive thanks to you both @volter9 @jimgwhit I haven't been able to spend much time on smvc recently too many deadlines as work.

**Pull request merged**
