### PR TITLE
3.0 - Final Phase, stage continued #3

### PR DESCRIPTION
**Pull request by LuckyCyborg**
### WIP - DO NOT MERGE

### CODE REVIEW

**Comment by tomvlk** [comment]
Could you please throw an exception for the truncate on sqlite. That's more suitable.

**Comment by tomvlk** [comment]
@LuckyCyborg There is no support for truncate in all versions for SQLite.

**Comment by LuckyCyborg** [comment]
@tomvlk Nice one! :smirk: 

I will do it.

**Comment by LuckyCyborg** [comment]
@daveismyname and @tomvlk Okay, I will continue on another pull-request.

Looks that now we have a **DBAL** in a good shape, then the objectives are completed.

Dave, you are gentle to merge this pull-request?

**Comment by tomvlk** [comment]
@LuckyCyborg If you have time for it you could prepare some structure for it. I need to work on something else until tonight.

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, Tom!

How about to move your **DBAL Demos** in our already existent module **Demos**? Or you want one specially for the them?

Anyway, I am on opinion to go our Demos in Module(s), the leave the App's Controllers area free for Dave's ones... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Great one, not only leaving the app controllers as clean as possible but also clean for installation. No messing in there.
Maybe make a documentation module(s) to make an interactive demo and documentation for some parts of the framework.

**Comment by LuckyCyborg** [comment]
@tomvlk I will move them and introduce the Theming, but in several hours, in my current develop pull-request #302; because in 45 min begins our presentation about **The State of The Nova Framework**. :smirk: 

I for one, I believe that everything will be OKay, the Nova is in good shape now. :+1:

**Pull request merged**
