### PR TITLE
Updated SimpleCurl with more HTTP methods and more

### PR DESCRIPTION
**Pull request by fabioassuncao**
Updated class Database with more method useful
Updated send mail with config class
New class Collection
Updated data class with serialize contents
Updated SimpleCurl with more HTTP methods

### CODE REVIEW

**Comment by jimgwhit** [comment]
Man that is crazy how are you wanting to change the database class no offense to you but you don't want to select star from the database sometimes you just want to select certain fiields. Dave please please don't update this.

**Comment by jimgwhit** [comment]
Again no offense but that code scares the living CRA blank blank out of me. Let's leave the database class alone and if you want a custom class for your own self then by all means use your class but dude please leave the database class alone its working geez.

**Comment by jimgwhit** [comment]
Any updates to any of the classes or any helpers should not break current code for someone who has production sites and place.

**Comment by daveismyname** [comment]
Sorry I cannot accept these changes, the classes need to be generic enough to be useful but not break existing code.

All classes should adhere to PRS 1 & 2 standards, these do not.
Some of the new methods could be useful but need to use the PSR standards also the changes you propose to the database class force certain columns to exists in all tables. 

Mail config options should be within the helper itself instead of in the core config class.

Comments should be in english

**Comment by Volter9** [comment]
No offense, but I find it ironic that this guy [copied](https://github.com/fabioassuncao/babita) Dave's framework and gave the credit to himself or deleted the `author` tag at all (most of these files).

So, what do ya think? :smile:

**Comment by daveismyname** [comment]
it's not the first time someone has extracted huge parts of the framework and removed all credit as if they have written it all, I find that sad. It would be better to honour the original authors of the components. SMVC has some brilliant user written helpers/controllers.

I mean you look at the commits, they start from the 24th of June yet classes contain dates that predate this such as 27 June, 2014.

I don't understand why the authors have been removed, it's a sign of respect to keep them. Like the ones I've seen before this I doubt anything will come of this.

**Comment by fabioassuncao** [comment]
daveismyname, I am sorry for what happened. I will have more care when making any new commit, I dexei me take the excitement and did silly. Regarding credits, did a project that uses much of the SMVC among others, removed the credit code by political issues of the organization but will immediately including the original authors. Finally, I ask my sincere apologies, I will do the correction and I regard myself the next time.

**Comment by daveismyname** [comment]
Thanks I appreciate that, regarding the commits trying to maintain a standard makes it a lot easier for everyone to share and use the code.

I've using the PRS standards check out their website if your not familiar with them. http://www.php-fig.org/psr/

**Comment by fabioassuncao** [comment]
daveismyname, updated the project with appropriate references to the authors. I know the PSR's, will keep the organization and follow the pattern in the next commit. Thank you, sorry for the hassle.

**Comment by daveismyname** [comment]
many thanks.

**Comment by jimgwhit** [comment]
Dave and fabioassuncao, Please if a major component is updated in a pull request, let it be a graceful change that doesn't break current production code.  Likewise if something is real major, add detailed comments and examples as to how to quickly make the changes so the production sites aren't down a long time.  I've used SMVC since it was brand new.  
Take the changes from version 2.1 to version 2.2, that is a major step, but announcements were made and folks had time to re-write code as necessary.  If a pull request will "break" the current way everything works, then don't do it, rather make it a whole new version.  But please please comment major changes well with code examples as to what and how to implement the changes.  
I imagine the version that will support php 7.*.* back to php 5.5.* will be major code changes.  But I am sure it will be well commented and a video to help us.  Dave so far you have done a great job with the updates, making them a smooth transition.  That's all I ask of any update or pull request.  Thanks.

**Comment by jimgwhit** [comment]
A further note, take the CSRF helper I did, and later OmarElGabry improved it.  Look at the code, he made sure detailed instructions were given.  Yes his change would "break" current code, but since he included very detailed instructions as to how to make the changes it turned out to be a smooth and easy change over.  This is how any pull request should be, have detailed instructions if it is a "code breaker".  
Now there has been updates to the router without detailed instructions, but that was different, as you could replace the router without any other code being broke. And Dave, thanks again for monitoring changes the way you have.

**Pull request closed without merging**
