### PR TITLE
3.0 - Doctrine DBAL based support #1

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Initial implementation.

### CODE REVIEW

**Comment by tomvlk** [comment]
@LuckyCyborg Please leave the current engines as it is until the tests have been replaced and refactored for the new DBAL and services.

**Comment by LuckyCyborg** [comment]
@tomvlk Worry not! I will implement our little **ORM** in, well... **\Nova\ORM** :smirk:

**Comment by tomvlk** [comment]
Weowowwowowo take it easy :laughing: keep some work for me please.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Weowowwowowo take it easy :laughing: keep some work for me please. 

Correction: **We** will implement our little **ORM** in, well.. **\Nova\ORM**. That's better? :smile:

**Comment by tomvlk** [comment]
Good enough haha

**Comment by LuckyCyborg** [comment]
@tomvlk Let's say that on the (mini-)**ORM** part we will make the skeleton and you will polish it and complete. You are in? :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Great!

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, Tom!

But, I expect you comments and your hands into **DBAL** thing, also... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Of course, Non ti preoccupare

**Comment by tomvlk** [comment]
@LuckyCyborg Btw, what about to make this:
**\Nova\Database\Entity** for using in generic entities.
**\Nova\ORM\Entity** extends **\Nova\Database\Entity** for use with ORM methods, like save, update, find, etc.

**Comment by LuckyCyborg** [comment]
@tomvlk Good one! Nothing against.

But, lets arrive to ORM... :smirk: 

You, meantime, do a eagle-flight over the simple ORM implementations. I wait to give me some opinions and suggestion on that theme... :smile:

**Comment by LuckyCyborg** [comment]
@tomvlk And there we go!

Right now, in theory we are ready to return a **\Nova\DBAL\Connection** from DBAL Manager...

**Comment by tomvlk** [comment]
## ORM Idea
#### Entity
The entities need to extend **\Nova\ORM\Entity** and use Annotations (customized annotations we create in our ORM\Annotations\ namespace) for table name, column names and database link name.

Sample entity:
```php
/**
 * Car Entity
 * @Table(name="car")
 **/
class Car extends Entity 
{
  /**
   * @var string
   * @Primary
   * @Column(type="int")
   **/
  public $carid;

  /**
   * @var string
   * @Column(type="string")
   **/
  public $make;

  /**
   * @var string
   * @Column(type="string")
   **/
  public $model;

  /**
   * @var double
   * @Column(type="double")
   **/
  public $costs;

  /**
   * @var string
   * @Column(type="string")
   * @Null
   **/
  public $type;
}
```
Or we could stick with the protected Entity variables for determinating table name, primary key etc.


#### ORM Methods
I was thinking of the following methods, remember, $car is an car already fetched from the database:
```php
$car->save(); // Save the entity, or update when already exists.
$car->update(); // Only update, will not create.
$car->create(); // Only insert, no update!
$car->delete(); // Will delete it from the db

$select = Car::find();
$car = $select->one()->where(array('carid' => 1))->fetch();
// $car wil be a single Car instance.

$allCars = $select->all()->fetch();
// $allCars will be an array with Car instances
```

**Comment by LuckyCyborg** [comment]
@tomvlk You got right the **Entity** structure, with its **Annotations**. See that you figured immediately how to use the shiny things coming with **Doctrine DBAL** ? ;smirk:

About the composite select methods, lets see what the **QueryBuilder** permit...

**Comment by tomvlk** [comment]
@LuckyCyborg Ye, the select isn't really been done. But that is dependent on the QueryBuilder indeed.
I will start on the **Entity** in the upcoming few days. But for sure around Monday late and Tuesday.

**Comment by LuckyCyborg** [comment]
@tomvlk The **select** method is there. Look on #356

**Comment by tomvlk** [comment]
@LuckyCyborg Just saw it! I think we still need to test our own **Connection** we extend from Doctrine, as we change it a bit and will add some helpfull methods and tools into it. Like the counter and select.

**Comment by LuckyCyborg** [comment]
@tomvlk Of course we need to test it. :smirk: 

I will implement late today an example/demo/test for this **DBAL** and you are free to make your Tests, too... :smile:

**Comment by tomvlk** [comment]
@LuckyCyborg Keep it easy, don't over rush it. We don't even know what Dave thinks about this, But I'm sure he gonna love the Doctrine QueryBuilder for sure!

**Comment by tomvlk** [comment]
@LuckyCyborg Maybe an idea to use our manager (dbal manager) to get a query builder directly, without having to go to the getConnection and then use the getQueryBuilder. Just for easy.

Btw: See manager, line nr 19, typo!

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Btw: See manager, line nr 19, typo!

Enlighten me, what typo?

**Comment by tomvlk** [comment]
https://github.com/simple-mvc-framework/framework/blob/3.0-beta/system/DBAL/Manager.php#L19
nstances  -> instances

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks! I seen it!

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Maybe an idea to use our manager (dbal manager) to get a query builder directly, without having to go to the getConnection and then use the getQueryBuilder. Just for easy.

Hmmm... But, practically the things are transparently and are supposed to be managed in **Model**.

Remember? It is supposed that when you use a **Model** (or **Entity** ?) you should already have a well configured and initiated **Database Connection**.

**Comment by tomvlk** [comment]
Yep, But in case anyone doesn't want to use the Model/Entity (ORM). And still want the QueryBuilder.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> We don't even know what Dave thinks about this, But I'm sure he gonna love the Doctrine QueryBuilder for sure!

Considering that he loved the **BaseModel**'s mini-QueryBuilder methods, I bet that he will be very satisfied to have one of most powerful QueryBuilder existent.

In other hand, if someone want to use the QueryBuilder part without Models/Entities, have just to get the **Connection** instance.

BUT, remember, Nova Framework is a **MVC** one, then is supposed to use Models there.

**Comment by tomvlk** [comment]
@LuckyCyborg Ye you are right about the models. But I mean why not create it for usage for in events for example, just small things.

Entity is normally supposed to be an table that will be used, the ORM.

**Comment by LuckyCyborg** [comment]
@tomvlk The Events aren't supposed to interact directly with **DBAL**. 

It is supposed those Events to invoke (live) Controllers or even bare Classes methods, who will call Model to do their jobs... :smirk:

**Pull request merged**
