### PR TITLE
3.0 - Final Phase, stage continued #16

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Optimize \Nova\Database\Service

### CODE REVIEW

**Comment by tomvlk** [comment]
Please change the fetch method in service to always fetch_class.

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks!

**Comment by LuckyCyborg** [comment]
@tomvlk In other hand, why you made the **$fetchMethod** configurable in child Services ?

**Comment by tomvlk** [comment]
That was before the multi engine support I think. 
But it always needs to fetch class on services. Then it would be an instance of the entity.

**Comment by LuckyCyborg** [comment]
@tomvlk OKay, then we force using \PDO::FETCH_CLASS in Service::read

**Comment by LuckyCyborg** [comment]
@daveismyname Please merge this pull-request, as being complete as objective!

**Pull request merged**
