### PR TITLE
Fix small issues in Pagination

### PR DESCRIPTION
**Pull request by g5pw**
These two commits fix some small issues with formatting/structure to fully adthere to bootstrap's way of doing things.

### CODE REVIEW

**Comment by jimgwhit** [comment]
Where is the sr-only coming from?

**Comment by jimgwhit** [comment]
Where is the sr-only coming from? How does it work?

**Comment by g5pw** [comment]
The sr-only is a standard bootstrap class, it's used multiple times in the Pagination.php class.
Its contents are hidden to normal users, but shown when a page is read by a screen reader.

I added this patch only because I saw it was used, but in some places it was used incorrectly, and this patch rectifies that.

**Comment by g5pw** [comment]
See [here](http://stackoverflow.com/questions/19758598/what-is-sr-only-in-bootstrap-3) for more information on the sr-only class

**Comment by jimgwhit** [comment]
What is a screen reader? I don't use bootstrap.

**Comment by daveismyname** [comment]
Thanks for this @g5pw @jimgwhit screen readers are software programs that allow blind or visually impaired users to read the text that is displayed on the computer screen with a speech synthesizer or braille display. A screen reader is the interface between the computer's operating system, its applications, and the user.

it's good to support accessibility to make things easier for people with disabilities.

**Comment by jimgwhit** [comment]
Thanks, I learned something new.

**Comment by geomorillo** [comment]
I dont use bootstrap i use semanticui does this affect my css?

**Comment by daveismyname** [comment]
no it's a class being used if you don't have any css for the class it simply won't do anything.

the css for it is this:

````
.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0,0,0,0);
    border: 0;
}
````

More details can be see at http://stackoverflow.com/questions/19758598/what-is-sr-only-in-bootstrap-3?answertab=votes#tab-top

**Comment by g5pw** [comment]
Thanks for the merge and good work on the project! :smile:

**Comment by geomorillo** [comment]
thansk

**Pull request merged**
