### PR TITLE
Reworking database helper into better organized database connectors

### PR DESCRIPTION
**Pull request by tomvlk**
To use the database from now on:

```php
$connection = EngineFactory::getEngine();
```
This will return an instance based on your Config.php. 

This structure will allow multiple so called drivers to operate all the same. 
Will also mark the \Helpers\Database as deprecated as it doesn't really belong there anymore, feel free to remove it later.

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk Just to note that we started, with Dave's knowledge, the encapsulation of the System components into namespace **\Smvc**. The System refactoring Pull Request incoming in short time, max. tomorrow.

Then, for example, your **\Core\Database** namespace will become **\Smvc\Core\Database**. Be prepared, to not appear conflicts... :smirk: 

All the best!

**Comment by tomvlk** [comment]
Yep, I already read. I will also add a pull request today for a new service implementation. You will love it! :+1: 
When there are conflicts, i'm open to solve it manually.

**Comment by LuckyCyborg** [comment]
You make me curious! :smile:

**Comment by daveismyname** [comment]
how will database calls be made from now on?

**Comment by tomvlk** [comment]
You can use this from now:

```php
$db = EngineFactory::getEngine(); // Will get default driver, from DB_TYPE and all other config.php constants
$results = $db->select("SELECT * FROM " . PREFIX . "car;"); // Handle it just like the \Helpers\Database
var_dump($results); // Result just the same way.
```

Or use the Entity (what was my Service Layer before) for full Object Oriented handling:
** Will be added in other pull request **

**Comment by daveismyname** [comment]
sounds good, what do you think to altering the select to leave out the select so you can do:

````
$db->select("column FROM ".PREFIX."car");
````

**Comment by tomvlk** [comment]
That would also be cool. And that will append SELECT * to the query right?
I will update this pull soon with some more, so please hang on :tractor:

**Comment by daveismyname** [comment]
Yes it's bothered me for ages but didn't want to break what people use but since we are making changes might as well do everything.

**Comment by kowston** [comment]
Yeah go for it, the double select has always bothered me.

**Comment by tomvlk** [comment]
Done :+1:

**Comment by daveismyname** [comment]
thanks!

**Comment by daveismyname** [comment]
Any chance you can provide a bit of an overview of what this brings in?

**Comment by tomvlk** [comment]
Will do a next pull request with more functionality (like my Service thing but reworked) and this will highly works on this.

But in general this will provide in resolving the issue when using other databases like PostgreSQL or smilary with the framework. The interface on how to use the Engine is always the same for every *Engine there will be. So it will work (almost) the same for MySQL as for PostgreSQL (I'm pretty sure this needs testing and tweaks when doing any).

**Comment by tomvlk** [comment]
Also see https://github.com/simple-mvc-framework/framework/pull/243

**Pull request merged**
