### PR TITLE
3.0 - Final Phase, stage continued #24

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Refactoring of **\App\Core\BaseModel**, on using only the **camelCase** variables and methods and overall optimizations.

The BaseModel lose the ability to use the **snake_case** methods, but its logic is simplified and consolidated.

### CODE REVIEW

**Comment by tomvlk** [comment]
@LuckyCyborg :100: :+1:

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks!

But the truth is that was cancelled the specification about compatibility with our "old-style" Components, using snake_case. So, time to simplify the BaseModel! :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, we wait your **updateBatch** method in Database Engines... :smirk: 

To see what we expect, look in the BaseModel's one.

**Comment by LuckyCyborg** [comment]
@tomvlk Also, I believe that a variable called **$callbackParameters** is Spanish enough to be on your like... :smirk:

**Comment by tomvlk** [comment]
Working on it now. Why all spanish btw..? :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk Very descriptive names on a somewhat complex Class.

Worry not, I will fight with their naming! :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, the Engine's updateBatch will be very nice to have ability to optionally use a **Transaction**.

Not in our specifications, but very useful overall. :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg I have it working currently, implemented on engine and service. But we should also implement multiple $where keys, for multi primary key support. Currently not done in my forked branch.
I don't have the whole day (not even half) for this unfortunately, also implementing the transaction isn't going to be today. Maybe you could assist in this.

**Comment by LuckyCyborg** [comment]
@tomvlk The principle of **updateBatch** is to have a unique **WHERE KEY**; for example, as... in example: **title**.

Then maybe multiKeys shall be in another method. 

In other hand, after you design arrive in the main repo, I will look for, too. :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg It can have an array with key columns or a string maybe.

**Comment by LuckyCyborg** [comment]
@tomvlk Again, see there:

```php
$data = array(
          array(
              'title'  => 'My title',
              'body'   => 'body 1'
          ),
          array(
              'title'  => 'Another Title',
              'body'   => 'body 2'
          )
      );
```

The method known the key, and for every record do the match:

```SQL
WHERE title = `My title`

WHERE title = `Another title`
```

**Comment by tomvlk** [comment]
@LuckyCyborg This is how it's done right now.

**Comment by LuckyCyborg** [comment]
@tomvlk Then everything is perfect! :+1:

**Comment by tomvlk** [comment]
But it would be cool to have support for this form too:

```php
updateBatch($data, array('title', 'subtitle'));
```
And will produce SQL:
```sql
WHERE title = 'My title' AND subtitle = 'Subtitle Value'

WHERE title = 'Another title' AND subtitle = 'Subtitle Value'
```

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, there was an example, but in real world, most likelly will be something like:

```
SET body = `body 1` WHERE id = 432

SET body = `body 2` WHERE id = 865
```

**Comment by LuckyCyborg** [comment]
@tomvlk If you made this **optionally**

as in both

```php
updateBatch($data, 'id');

updateBatch($data, array('title', 'subtitle'));
```

I don't have nothing against. But what we need is the first variant. :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Thats the plan, but not for now, as I don't have the time and concentration rates for it :smiley:

**Comment by LuckyCyborg** [comment]
@tomvlk OKay, then! :+1:

**Comment by LuckyCyborg** [comment]
@daveismyname Please merge this pull-request, as being completed as objectives!

**Pull request merged**
