### PR TITLE
Initial implementation of \Nova\ORM\Connection\Adapter and \Nova\ORM\…

### PR DESCRIPTION
**Pull request by LuckyCyborg**
…Connection\Wrapper

### CODE REVIEW

**Comment by tomvlk** [comment]
@LuckyCyborg It was the purpose that you create a package of it! Same as I do..

**Comment by LuckyCyborg** [comment]
@tomvlk Sorry Tom, but you have to read again the Issue, was about:

## You will continue the Nova's built-in ORM or we will take over?

You clearly stated that **you abandoned** the **Nova's ORM** and see there what asked Dave:

> For the ORM @LuckyCyborg are you looking to take over \Nova\ORM or happy to use @tomvlk's once it's ready as a third party package?

### My response was:

> @daveismyname I think that I would continue the Tom's work on \Nova\ORM and to implement something simple, supporting the basic Entity relations: hasOne, hasMany, belongsTo

**Comment by tomvlk** [comment]
> @tomvlk I'm in the same position for my company CRM projects it's needed but won't be part of the public framework it's too specific.

I really think that its better to have it as a package as the ORM is really specific!

**Comment by LuckyCyborg** [comment]
@tomvlk 

> I really think that its better to have it as a package as the ORM is really specific!

Perfect! That's your opinion and I respect it! Also, all of my colleagues respect your opinion! :smirk: 

But, in your case, we consider an ORM as **a usual thing** for a Framework; and we need a simple, and fast but generic ORM, implementing the usual **Relations** and well integrated into **MVC**.

Note the Keyword. **MVC**, aka **Model, View, Controller**.

The big difference between your ORM and our ORM is that the second one will be well integrated into Nova, will be smaller, faster and not as last, it will sport a **Model**.

**Comment by tomvlk** [comment]
SweetORM will be integrated too btw. In the MVC, in any MVC!

**Comment by LuckyCyborg** [comment]
@tomvlk Nice to know!

BUT, Tom! 

# You abandoned the Nova's ORM!

Then, I ask you to be kind to explain WHY we have that discussion, while was stated clear that we will implement us the **abandoned** Nova's ORM?

**Comment by tomvlk** [comment]
Somewhere you recommended to move to a package, thats why :trollface: .
So you said it on purpose.. ?

**Comment by LuckyCyborg** [comment]
@tomvlk I recommended you to choose between using the Nova's native API, if you want to keep your work into System, **OR** to go into a **Nova Package** and use the Doctrine based DBAL.

Even **I've written for you** a **Database Wrapper** supporting **unnamed parameters binding**, able to drive your ORM almost untouched, in the top of **Nova\Database**! 

Also, I said right to you: **Look, Tom, your ORM is fine and kicking, almost untouched and we written for you a Database Wrapper specially to support your Vision.**

You remember what you responded? That you started your own **ORM**, totally independent by Nova.

I even open an Issue about this **Nova's ORM** future and the eventual take-over. Was discussed, was debated, even was made decisions, together with @daveismyname .

That's **why** I don't understand your point. Sorry, but really I do not understand.

**Pull request merged**
