### PR TITLE
3.0 - Final Phase, stage continued #4

### PR DESCRIPTION
**Pull request by LuckyCyborg**
### WIP - DO NOT MERGE

### CODE REVIEW

**Comment by tomvlk** [comment]
@LuckyCyborg Be gentle with the engines :pray:

**Comment by LuckyCyborg** [comment]
@tomvlk Unlucky push from one of my colleagues...

Fixed fast the things, like you see! :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg The selectone and selectall are great to have. We need good documentation on this btw.

**Comment by LuckyCyborg** [comment]
@tomvlk Yeah, those two simplify the code and make it more, let's say... readable. :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk There, in \Nova\Database\Service,  I have a question for you:

You use a similar to **selectAll** or **selectOne** ?

```php
    public function read($sql, $bindParams = array())
    {
        return $this->engine->select($sql, $bindParams, $this->fetchMethod, $this->fetchClass);
    }
```

**Comment by tomvlk** [comment]
@LuckyCyborg So you really changed connectionName to linkName ha. I saw it!

**Comment by LuckyCyborg** [comment]
@tomvlk Ooops! I did it? :100: 

Come one, my friend, you know well that **Database Connection <--> Database Link** :smirk: 

Hey, but I tried to be as Spanish I can there!

You like the variable name **$multipleInserts** ,  right?

**Comment by LuckyCyborg** [comment]
Now I should prepare to go to Conference Room for the Briefing/Presentation...

See you later, my friend! :+1:

**Comment by LuckyCyborg** [comment]
@tomvlk and @daveismyname Okay, lets **merge all pull-requests** now, to initiate the moving of **Database Demos** into **Demo** Module!

**Comment by tomvlk** [comment]
@LuckyCyborg Please remove last commit. I'm fully rewriting the demo's and make it better with menu for different demos. 
Will be sweat!

**Comment by LuckyCyborg** [comment]
I just positioned the Controller. Or you work right there?

**Comment by tomvlk** [comment]
@LuckyCyborg Ye, and it will be removed too. I'm working on a demo index page with links to different demo's, categorised etc

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, then...

**Comment by tomvlk** [comment]
perfect, merge ready :trophy: :+1:

**Comment by LuckyCyborg** [comment]
@daveismyname Please, then, merge this pull request!

**Pull request merged**
