### PR TITLE
Replacement of SMVC Router with an Improved Routing

### PR DESCRIPTION
**Pull request by LuckyCyborg**
This pull request contains the Improved Routing components discussed on https://github.com/simple-mvc-framework/framework/issues/222

### CODE REVIEW

**Comment by jimgwhit** [comment]
I downloaded https://github.com/LuckyCyborg/simple-mvc-framework/tree/3.0-improved-routing and installed it just like @daveismyname ver 3 beta.  @daveismyname ver 3 beta is working with no issues, but I spent over 2 hours trying to get @LuckyCyborg  to work, all I ever get is a blank white screen.  
It was install exactly like Daves ver 3 beta.  In fact controllers, models, views were just copied over.  
Oh, I'm not getting any errors in the error.log neither.

**Comment by jimgwhit** [comment]
Forgot to ask, has it been tested on php 7, I am developing in php 5.6 and that's where it's not working as stated above.  No offence to anyone, but if a big change to router, why don't we just adapt the one Laravel uses?

**Comment by LuckyCyborg** [comment]
@jimgwhit It is supposed to be a Routing replacement, sure that the code is identical with the @daveismyname default tree, considering the rest of framwork. ;)

In other hand, is developed under PHP 5.6.x, intensive tested under PHP 5.5.x and some (but working) tests was made under PHP 7.0. I hope to see the feedback about how it works in another cases.

Our PHP version target is literally PHP 5.5.x with (future) support for PHP 5.6.x, as Project objectives. Sure, the PHP 7.0 can't be ignored, so we wait your opinions.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

Looks like something was gone wrong with the commit executed by my colleague.

Please try to update your local tree, seems like everything is OK now.

**Comment by jimgwhit** [comment]
No didn't see the config file change at first, was following the readme.md instructions. Please if you do a pull request update all affected files.  The Dag Gum thing works now, no errors so far.  
Funny I am the only one testing stuff and at least reporting back.  Please ensure all latest updates are actually in the pull request.
Where are all the other testers?  See @daveismyname I may get worried at times, but I hang it there, and test, report back, etc.  I think some of the others just like throwing in a comment.  I spend hours testing stuff.  Remember me and @volter9 did extensive test on previous router, so cut me a break.  Let me rant a little at times.

**Comment by LuckyCyborg** [comment]
@jimgwhit Thanks for your efforts, I'm happy that now you have a function SVMC driven by our Routing. And your previous experience on SVMC's Routing make you a *Valuable Enemy* for us. We hope that you'll continue the tests and I wait your reports.

Please, continue also your QUERY_STRING tests and report back if something looks changed. Like I said, there should be no differences, compared with the Macaw Son, and also we are interested in your opinion about the Routing speed performances. Similar? Slower? Faster?

All the best!

**Comment by jimgwhit** [comment]
@LuckyCyborg This is for the new version 3 beta right?

**Comment by LuckyCyborg** [comment]
@jimgwhit Yep! But is it supposed to works out-of-box in a **2.2 stable** setup too...

Still you need to integrate it manually. See the details given in the another thread.

But, in principle is simple to port our Routing into **2.2 stable** tree: add the supplementary Methods in **Request** and **Url** helpers, replace the **Router** and add the **Route**, then modify the **index.php** and the define in the **\Core\Config**.

If you need the **ClassicRouter**, watch for the right namespace: **App\Core** -> **\Core**

**Comment by daveismyname** [comment]
I'm testing this out not, I was busy last night.

I've downloaded the zip from https://github.com/LuckyCyborg/simple-mvc-framework/tree/3.0-improved-routing unzipped and placed in my localserver renamed the base folder to simple-mvc-framework-3

renamed and setup Config.php and .htaccess I can see the defualt page but when going to the subpage I'm getting a 404 page.

Have I missed a step?

**Comment by LuckyCyborg** [comment]
@daveismyname  Strange! I downloaded too the zip file, right now, configured and installed in a shared hosting, with the **webroot** pointing in the public directory. Everything works OK, see there:

http://smvc3.giulianaeassociati.com/

I will test on several hours (I'm not on our Office right now), also the local installation right on your style, to see what happened.

BTW, you adjusted on **.htaccess** the **RewriteBase** ? In you case (sub-directory installation), I believe that it shall be:

```
RewriteBase /simple-mvc-framework-3/public/
```

**Comment by daveismyname** [comment]
ah of course I missed public from the paths! my bad it's working now thanks.

Sorry to ask but with the many posts it's hard to keep track of the changes / discussions can you maybe give an overall summary of what's now possible with this new router?

**Comment by LuckyCyborg** [comment]
@daveismyname I will give you a summary today, in several hours, when I will return to Office. Right now I'm run in highway, sorry for delay... :)

**Comment by daveismyname** [comment]
I understand many thanks for your help.

**Comment by LuckyCyborg** [comment]
@daveismyname A quick; the most important post, were is described everything in detail, is following (sorry for quick copy&paste!).

OK, then my suggestion to enhance the Routing in the SVMC 3.0; offering a better support to further enhance the Router, if is the case.

Additional method on **\Helpers\Request**

```php
    /**
     * Gets the request method.
     *
     * @return string
     */
    public static function getMethod() {
        $method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : 'GET';

        if (isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'])) {
            $method = $_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'];
        }
        elseif (isset($_REQUEST['_method'])) {
            $method = $_REQUEST['_method'];
        }

        return strtoupper($method);
    }
```
Additional method to **\Helpers\Url**

```php
    public static function detectUri()
    {
        $requestUri = $_SERVER['REQUEST_URI'];
        $scriptName = $_SERVER['SCRIPT_NAME'];

        $pathName = dirname($scriptName);

        if (strpos($requestUri, $scriptName) === 0) {
            $requestUri = substr($requestUri, strlen($scriptName));
        }
        else if (strpos($requestUri, $pathName) === 0) {
            $requestUri = substr($requestUri, strlen($pathName));
        }

        if (($requestUri == '/') || empty($requestUri)) {
            return '/';
        }

        $uri = parse_url($requestUri, PHP_URL_PATH);

        return str_replace(array('//', '../'), '/', ltrim($uri, '/'));
    }
```

A new class, **\Core\Route**

```php
namespace Core;

/**
 * The Route class is responsible for routing an HTTP request to an assigned callback function.
 * The Router tries to match the requested URL against a series of URL patterns.
 */
class Route
{
    /**
     * @var string HTTP method or 'ANY'
     */
    private $method;

    /**
     * @var string URL pattern
     */
    private $pattern;

    /**
     * @var mixed Callback
     */
    private $callback = null;

    /**
     * @var array Route parameters
     */
    private $params = array();

    /**
     * @var string Matching regular expression
     */
    private $regex;

    /**
     * Constructor.
     *
     * @param string $method HTTP method
     * @param string $pattern URL pattern
     * @param mixed $callback Callback function
     */
    public function __construct($method, $pattern, $callback)
    {
        $this->method   = $method;
        $this->pattern  = $pattern;
        $this->callback = $callback;
    }

    /**
     * Checks if a URL and  HTTP method matches the Route pattern.
     *
     * @param string $uri Requested URL
     * @param string $method HTTP method
     * @return boolean Match status
     */
    public function match($uri, $method)
    {
        if (($this->method != $method) && ($this->method != 'ANY')) {
            return false;
        }

        // Wildcard or exact match.
        if (($this->pattern === '*') || ($this->pattern === $uri)) {
            return true;
        }

        $last_char = substr($this->pattern, -1);

        // Build the regex for matching.
        if (strpos($this->pattern, ':') !== false) {
            $regex = str_replace(
                array(':any', ':num', ':all', ':hex', ':uuidV4'),
                array('[^/]+', '-?[0-9]+', '.*', '[[:xdigit:]]+', '\w{8}-\w{4}-\w{4}-\w{4}-\w{12}'),
                $this->pattern
            );
        }
        else {
            $regex = $this->pattern;
        }

        $regex = str_replace(array('(/', ')', '/*'), array('(?:/', ')?', '(/?|/.*?)'), $regex);

        // Fix trailing slash.
        if ($last_char === '/') {
            $regex .= '?';
        }
        // Allow trailing slash.
        else {
            $regex .= '/?';
        }

        // Attempt to match the Route and extract the parameters.
        if (preg_match('#^' .$regex .'(?:\?.*)?$#i', $uri, $matches)) {
            // Remove $matched[0] as [1] is the first parameter.
            array_shift($matches);
            // Store the extracted parameters.
            $this->params = $matches;
            // Also, store the compiled regex.
            $this->regex = $regex;

            return true;
        }

        return false;
    }

    //
    // Some Getters

    public function callback()
    {
        return $this->callback;
    }

    public function params()
    {
        return $this->params;
    }

    public function regex()
    {
        return $this->regex;
    }

}
```
The (rewritten) class **\Core\Router**

```php
namespace Core;

use Core\Route;
use Helpers\Request;
use Helpers\Url;

/**
 * Router class will load requested controller / closure based on url.
 */
class Router
{
    private static $instance;

    /**
     * Array of routes
     *
     * @var array $routes
     */
    private $routes = array();

    /**
     * Set an Error Callback
     *
     * @var null $errorCallback
     */
    private $errorCallback = '\Core\Error@index';


    // Constructor
    public function __construct()
    {
        self::$instance =& $this;
    }

    public static function &getInstance()
    {
        if(! self::$instance) {
            $appRouter = APPROUTER;

            self::$instance = new $appRouter();
        }

        return self::$instance;
    }

    /**
     * Defines a route with or without Callback and Method.
     *
     * @param string $method
     * @param array @params
     */
    public static function __callStatic($method, $params)
    {
        $router = self::getInstance();

        $router->addRoute($method, $params[0], $params[1]);
    }

    /**
     * Defines callback if route is not found.
     *
     * @param string $callback
     */
    public static function error($callback)
    {
        $router = self::getInstance();

        $router->callback($callback);
    }

    public function callback($callback = null)
    {
        if(is_null($callback)) {
            return $this->errorCallback;
        }

        $this->errorCallback = $callback;
    }

    /**
     * Maps a Method and URL pattern to a Callback.
     *
     * @param string $method HTTP metod to match
     * @param string $pattern URL pattern to match
     * @param callback $callback Callback object
     */
    public function addRoute($method, $route, $callback)
    {
        $method = strtoupper($method);
        $pattern = ltrim($route, '/');

        $route = new Route($method, $pattern, $callback);

        array_push($this->routes, $route);
    }

    /**
     * Invoke the callback with its associated parameters.
     *
     * @param  object $callback
     * @param  array  $params array of matched parameters
     * @param  string $message
     */
    protected function invokeObject($callback, $params = array())
    {
        if (is_object($callback)) {
            // Call the Closure.
            return call_user_func_array($callback, $params);
        }

        // Call the object Controller and its Method.
        $segments = explode('@', $callback);

        $controller = $segments[0];
        $method     = $segments[1];

        // Initialize the Controller
        $controller = new $controller();

        // Execute the Controller's Method with the given arguments.
        return call_user_func_array(array($controller, $method), $params);
    }

    public function dispatch()
    {
        // Detect the URI and the HTTP Method.
        $uri = Url::detectUri();

        $method = Request::getMethod();

        foreach ($this->routes as $route) {
            if ($route->match($uri, $method)) {
                // Found a valid Route; invoke the Route's Callback and go out.
                $this->invokeObject($route->callback(), $route->params());

                return true;
            }
        }

        // No valid Route found; invoke the Error Callback with the current URI as parameter.
        $params = array(
            htmlspecialchars($uri, ENT_COMPAT, 'ISO-8859-1', true)
        );

        $this->invokeObject($this->callback(), $params);

        return false;
    }

}
```

The new **\Core\Router** class is compatible as configuration with the standard one, offering also the ability to use optional parameters in patterns, so will work a pattern like:

**blog/archive(/:num(/:num(/:num)))**

This example pattern will match the URIs:
```
/blog/archive/2015/12/31
/blog/archive/2015/12
/blog/archive/2015
/blog/archive
```

To note that for a properly work, this new Router need a define in Config class, 

```php
/**
 * Set the Application Router.
 */
define('APPROUTER', '\Core\Router');
```

and a slightly different approach in **/public/index.php**

```php
// We should get the Router instance before to start Routes configuration.
$router = Router::getInstance();

// Load the Routes
include SYSTEM .'Core/routes.php';

// Execute matched routes
$router->dispatch();
```

Also, there is no **fallback** switch and no **autoDispatch**.

You'll notice that the new *\Core\Router* is very different from the orthodox one, and use only few static functions. But the best of the bests is that class can be easily extended; for example, if we want a *Classic Router*, running in ol'good style of AutoDispatching or like the CodeIgniter routes, there we go:

```php
namespace Core;

use Core\Route;
use Helpers\Request;
use Helpers\Url;

/**
 * ClassicRouter class will load requested controller / closure based on url.
 */
class ClassicRouter extends \Core\Router
{
    // Constructor
    public function __construct()
    {
        parent::__construct();
    }

   /**
     * Ability to call controllers in their module/directory/controller/method/param way.
     */
    public function autoDispatch($uri)
    {
        // NOTE: This Auto-Dispatch routing use the styles:
        //
        // <DIR><directory><controller><method><params>
        // <DIR><module><directory><controller><method><params>

        // Split the URI in the path components.
        $parts = explode('/', $uri);

        // Loop through URI parts, checking for the Controller file including its path.
        $controller = '';

        if(! empty($parts)) {
            // Classify, to permit: '<DIR>/file_manager/admin/' -> '<SMVC>/Modules/FileManager/Admin/
            $controller = str_replace(array('-', '_'), '', ucwords(array_shift($parts), '-_'));
        }

        // Verify if the first URI part match a Module.
        $testPath = SMVC.'Modules/'.$controller;

        if(! empty($controller) && is_dir($testPath)) {
            // Walking in a Module path.
            $moduleName = $controller;
            $basePath   = 'Modules/'.$controller.'/Controllers/';

            // Go further only if have other URI Parts, to permit URL mappings like:
            // '<DIR>/clients' -> '<SMVC>/Modules/Clients/Controllers/Clients.php'
            if(! empty($parts)) {
                $controller = str_replace(array('-', '_'), '', ucwords(array_shift($parts), '-_'));
            }
        }
        else {
            $moduleName = '';
            $basePath   = 'Controllers/';
        }

        // Check for a valid Controller even in sub-directories.
        $directory = '';

        while (! empty($parts)) {
            $testPath = SMVC.$basePath.$directory.$controller;

            if (! is_readable($testPath .'.php') && is_dir($testPath)) {
                $directory .= $controller .'/';
                $controller = str_replace(array('-', '_'), '', ucwords(array_shift($parts), '-_'));

                continue;
            }

            break;
        }

        // Get the normalized Controller
        $defaultOne = !empty($moduleName) ? $moduleName : DEFAULT_CONTROLLER;
        $controller = !empty($controller) ? $controller : $defaultOne;

        // Get the normalized Method
        $method = !empty($parts) ? array_shift($parts) : DEFAULT_METHOD;

        // Get the Controller's className.
        $controller = str_replace('/', '\\', 'App/'.$basePath.$directory.$controller);

        // Controller's Methods starting with '_' are not allowed also to be called on Router.
        if(($method[0] === '_') || !class_exists($controller)) {
            return false;
        }

        // Initialize the Controller
        $controller = new $controller();

        // Check for a valid public Controller's Method.
        if(! in_array(strtolower($method), array_map('strtolower', get_class_methods($controller)))) {
            return false;
        }

        // Execute the current Controller's Method with the given arguments.
        call_user_func_array(array($controller, $method), !empty($parts) ? $parts : array());

        return true;
    }

    public function dispatch()
    {
        // Detect the URI and the HTTP Method.
        $uri = Url::detectUri();

        $method = Request::getMethod();

        foreach ($this->routes as $route) {
            if ($route->match($uri, $method)) {
                // Found a valid Route; invoke the autoDispatch and go out.
                $callback = $route->callback();

                if(! is_object($callback)) {
                    $autoUri = preg_replace('#^' .$route->regex() .'$#', $callback, $uri);

                    $this->autoDispatch($autoUri);
                }
                else {
                    $this->invokeObject($callback, $route->params());
                }

                return true;
            }
        }

        // No valid Route found; invoke the Error Callback with the current URI as parameter.
        $params = array(
            htmlspecialchars($uri, ENT_COMPAT, 'ISO-8859-1', true)
        );

        $this->invokeObject($this->callback(), $params);

        return false;
    }

}
```

To activate the **ClassicRouter** we need to setup:

```php
/**
 * Set the Application Router.
 */
define('APPROUTER', '\Core\ClassicRouter');
```

To note that new **ClassicRouter** have much greater performance compared with the orthodox **autoDispatcher** method of the actual **\Core\Router**, supporting patterns, just like the base **\Core\Router**, and supporting also, very important, the sub-directories on App and Modules. Then, you can happily use, for example, for your controllers paths, the styles:
```
/admin/blog              -> /app/Controllers/Admin/Blog.php                @index
/user                    -> /app/Modules/User/Controllers/User.php         @index

/admin/users             -> as route pattern to following...
/user/admin/users/list   -> /app/Modules/User/Controllers/Admin/Users.php  @list
```

You can even do:

```php
Router::any('/admin/(:any)/(:all)', '$1/admin/$2');

OR

Router::any('/admin/(:any)/(:all)', '$1/admin/$1/$2');
```
which will map the following Routes like as: 
```
/admin/page/add     -> /page/admin/add     -> /app/Modules/Page/Controllers/Admin.php   @add
/admin/blog/view/15 -> /blog/admin/view/15 -> /app/Modules/Blog/Controllers/Admin.php   @view
/admin/users/edit/1 -> /users/admin/edit/1 -> /app/Modules/Users/Controllers/Admin.php  @edit

OR

/admin/page/add     -> /page/admin/page/add      -> /app/Modules/Page/Controllers/Admin/Page.php    @view
/admin/blog/view/15 -> /blog/admin/blog/view/15  -> /app/Modules/Blog/Controllers/Admin/Blog.php    @view
/admin/users/edit/1 -> /users/admin/users/edit/1 -> /app/Modules/Users/Controllers/Admin/Users.php  @edit
```
And, yeah, if the **SVMC 3.0** is driven by this enhanced Router, not only you have, native, a better Routing, but us we can easily extend the default Router to support our Asset Files Serving style and other things, without to completely replace the main thing.

Finally, I will ask if there is interest for a simple but very powerful **\Core\Language** class replacement, which support the PHP's 5.5.x native **INTL** (based on **ICU**), with support for single language file per App and Module or Template, loading multiple language domains, etc. It needs the **Config** class mentioned in my previous (long) post, some functions to be defined in index.php or a configuration file, but the result is somewhat similar with what can be seen in **CakePHP 3.0**

Example of usage:

```php
Session::set('message', array('type' => 'success', 'text' => __d('user', 'User <b>{0}</b> was Added', $userinfo['username'])));
```

Notice the function called **__d()**, that's command read the language file from the domain (of Module) **User** and translate the message with support for parameters.

BTW, our Language class have as companion a (Linux) script able to scan the PHP files from framework, to extract the translatable strings and to update the language files on App and Modules.

All the best!

**Comment by daveismyname** [comment]
to use the classic routes the setup as I understand it is to change the CONSTANT in Config.php to this

````
define('APPROUTER', '\App\Core\ClassicRouter');
````

I've done that but as soon as I go to the project root this error is fired:

````
Invalid argument supplied for foreach() in /app/Core/ClassicRouter.php on line 118
````

It appears the class is not calling the parent construct, since $routes is an array in the parent Router.php class.

Also with this proposed change will it be possible to use classic routes and named routes? since ClassicRouter extends Router

Also I've tried to use your example:

````
blog/archive(/:num(/:num(/:num)))
````

In a route using a closure
````
Router::any('test(/:num(/:num(/:num)))', function($one, $two, $three){
    echo "$one - $two - $three";
});
````

I've tried a few different combinations none of which I can get working, classic routes like this still work but must match the exact number of params in the url:

````
test/(:num)/(:num)
````

**Comment by jimgwhit** [comment]
@daveismyname  and @LuckyCyborg  see my latest comment under issue #222  where are you are talking about grouping, which I have no problem with, but maybe hold off on pushing this until the grouping thing is all worked out. That way it's a thoroughly retested router. In other words there are still tweaks happening here. Maybe wait till all tweaks are complete and test run.

**Comment by daveismyname** [comment]
@jimgwhit since there's sections not working for me yet I'm not going to commit it, I may be missing something but the only routes I can get working at the moment are the routes that already work. See my comment above.

**Comment by jimgwhit** [comment]
@daveismyname  yeah I saw your comment, and when I tested last night I only tested for a querystring and that worked. But now with the grouping thing that is something added since last night, so I'm confused on the define constants, should one define be used for the grouping thing and another define for the regular routing. I think you know what I mean you but two constants being used.

**Comment by LuckyCyborg** [comment]
@daveismyname I will look tomorrow to **ClassicRouter**. If I understand right, there are the problems.

In other hand, while base **Router** use the "modern" routes, and the **ClassicRouter** use the... classic routes, there is nothing that stop a third one, more complex, which use the both ways. As principle, our Design is to be easily extended.

**Comment by daveismyname** [comment]
@LuckyCyborg thanks I appreciate the effort you have put it, it looks really useful and more flexible then the current router just want to make sure I understand all the options as I need no doubt need to support others in it's use later on. 

The base Router works fine and names routes and filters (:num) etc but not for flexible params as far as I can tell, then the other problem is the classic router as you've mentioned.

I think it's useful to have the option to use a named route or a classic route for those that prefer them.

Personally I prefer named routes.

**Comment by jimgwhit** [comment]
So you don't have to jump back and forth here's my question on thathe
@LuckyCyborg  you have
~~~
$router = Router::getInstance();

$router->group('admin', function() {
    Router::get('/', 'App\Controllers\Admin\AdminController@index');
    Router::get('/some', 'App\Controllers\Admin\AdminController@some');
});
~~~
But what if admin controller is underneath controllers like
~~~
$router = Router::getInstance();

$router->group('admin', function() {
    Router::get('whatever/', 'App\Controllers\AdminController@whatEver');
    });
~~~
Also the same define is being used couldn't the define for the extended router be named something else that way regular routing and grouping could it still be done.  
Another question should the pull request be closed for now while you tweak this and then you could put in a new pull request after testing all.

**Comment by LuckyCyborg** [comment]
@daveismyname In principle is a veri important decision the routing style, so, in our opinion, the best for the end-user is to have ability to switch them, and to use one of the classes. Let's say that the Router offer Laravel style, while ClassicRouter, the CodeIgniter style.

@jimgwhit In principle, what Grouping do is to append a path prefix on routes. So,  

```
$router->group('admin', function() {
    Router::get('whatever/', 'App\Controllers\AdminController@whatEver');
    });
```

Is equivalent with:
```
 Router::get('admin/whatever/', 'App\Controllers\AdminController@whatEver');
```

**Comment by daveismyname** [comment]
@LuckyCyborg I agree that makes a lot of sense. if we can test both ways with your suggestions that would be great.

**Comment by LuckyCyborg** [comment]
And I'm here to assist you. :smile: 

I believe also that a well testing of the both ways is the best. You want us to concentrate into Classic Style? Why not! Let's test them!

You can describe the classic route which you tested, there?

**Comment by daveismyname** [comment]
I didn't get far with classic testing my first test was to call localhost/project/demo to call app/Controllers/Demo.php.

just looking over the other comment and noticed a section talking about asset server which I absolutely love the sound of that, I'd like to look at using that too, with it being weekend we can wait until next week that's not problem at all.

**Comment by LuckyCyborg** [comment]
@daveismyname I try to test and prepare the classic routing for your default welcome pages.

Talking about the Asset File Serving is a standard procedure used even by CakePHP and Laravel, to serve files, when the application is behind webroot. And, yes, we use in our Routing too.

In the proposed Routing variant, it was stripped down, to not scare you with the complexity. But, the Assets Serving can be reintroduced in quick time. The code is already there.

In other hand, you should remember that you talk, in our case, with some Corporate guys. For us, this Project is one of the job tasks. As, can be understand, in Weekend, my colleagues aren't available.

In other hand, I understand well that for you, this is a Hobby Project, and you have time for him right on the weekend. So, trying to do the best of two worlds, I will try spend this weekend keeping the contact with the SVMC community. Think that is the best... :smiley:

**Comment by daveismyname** [comment]
I think it would be good to put it back in, this is a hobby project but also I use this to build CRM projects for my main job so I try to keep my other projects structure inline as much as I can with the framework. 

Since I do majority of the work on my own I really value the community and people such as yourself.

**Comment by LuckyCyborg** [comment]
@daveismyname For me it is just a Job Task, but I really liked this little Micro-Framework, and I appreciate your ability to create tutorials for it. Good Job! :+1:

**Comment by tomvlk** [comment]
Isn't it better to name it Scope instead of group? Good work on the routing!
Anyway I really like this framework just because it's not too much blabla and easy to understand. Also works on multiple environments, and isn't limited on several php extension (like others do).

**Comment by LuckyCyborg** [comment]
@tomvlk Yeah, can be called Scope, or Group. Both works fine. To be honest, I prefer your variant.

@daveismyname well, the main bug was an **private -> protected**, and the auto-routing works, as can be seen in:

http://smvc3.giulianaeassociati.com/welcome/index
http://smvc3.giulianaeassociati.com/welcome/subpage

Yet, I hit another small problem about regex compatibility. which make problems with the route mapping.

BTW, I hope you'll ignore my debugging lines. :smirk:

**Comment by LuckyCyborg** [comment]
Ok, then. Now the ClassicRouting works in my tests, like there:

http://smvc3.giulianaeassociati.com/

Using the following routes for mapping:

```
Router::any('subpage', '/welcome/subpage');
Router::any('', '/welcome/index');
```

I still work on regex compatibility. It is used with the parameters. About something like:

```
Router::any('/admin/(:any)/(:all)', '$1/admin/$2');
```

**Comment by jimgwhit** [comment]
@tomvlk are you going to help with testing the router in various situations?

**Comment by LuckyCyborg** [comment]
OK, I managed to make the **ClassicRouter** to work, but possible the parameters do not works right, now. I you want to test it, I can do a push, in about 2 hours, when I will be back. Or you maybe want to wait the entire cake. Post there what you wish, I will read the posts in the next 2 hours (I go home). :+1:

**Comment by daveismyname** [comment]
I'll wait then I can test more at once.

Thanks again.

**Comment by LuckyCyborg** [comment]
Ok, the ClassicRouter now works as expected, with parameters being functional, also, tested and added examples for optional parameters route in routes.php, and tested in a real website all of our today offer.  Everything works as expected by us.

The main reason of those glitches was remained on the past of the **ClassicRouter** (about a week), comparative with the base Routing. Nothing major but disturbing.

To note that **the optional parameters make no sense for Classic Routing in the actual Design**, where the regex captures shall to match the insertions in processed route (second parameter, aka callback).

**Comment by daveismyname** [comment]
thanks this is working great, for classic router I agree there is no need to have routes defined in the routes file or make optional params let the controller method set those.

I've tested the named routes using exact matches and also optional params patterns using the examples you provided and also my own. All working great.

This is really good! :+1: 

I'll accept this PR now, since we are still in beta more testing is required but I'm happy to put this in the beta release.

Then if we can look at the asset serving next week that would be good. Using your recommend server from an assets folder from the sections (templates / modules)

**Pull request merged**
