### PR TITLE
return current month' number of days if month value is lower than 1 or bigger than 12

### PR DESCRIPTION
**Pull request by avenirer**

### CODE REVIEW

**Comment by avenirer** [comment]
May I know the reason why not accepting this pull request? Thank you.

**Comment by daveismyname** [comment]
I merged your more recent PR or have I got this wrong?

**Comment by avenirer** [comment]
actually there are two PR's on same file... with different modifications.

**Comment by avenirer** [comment]
Sorry about that, but I didn't want to do two different changes in the same pull request. I guessed I messed that up. Next time will be more careful.

**Comment by daveismyname** [comment]
actually I should have merged the first one first, doing it back to front has not caused conflicts, I'll correct that later or if you have time can you update the PR.

**Pull request closed without merging**
