### PR TITLE
3.0 - Final Phase, stage continued #5

### PR DESCRIPTION
**Pull request by LuckyCyborg**
This pull-request implements a complete Theming example and a complete Module classes flow for Demo Module.

@daveismyname Please merge it!

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk Look there:

http://smvc3.giulianaeassociati.com/demos/themed/welcome

**Comment by LuckyCyborg** [comment]
@BTW this style of Menu we use on **Backend**, where we do not need something more dynamic.

**Comment by daveismyname** [comment]
Love it!!!!!!

**Comment by tomvlk** [comment]
Great work!!!! Awesome!!!!

**Comment by LuckyCyborg** [comment]
@daveismyname and @tomvlk Thanks!

BTW, Tom, now it is you round to enter and to complete the run... :smirk:

**Pull request merged**
