### PR TITLE
3.0 - Final Phase, stage continued #20

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Improve checking of Entity's classPath in **\Nova\Database\Engine\Base**

Small but important change! Please merge it directly!

### CODE REVIEW

**Comment by tomvlk** [comment]
@LuckyCyborg Please update the phpdoc too, Base: 162 and 163 (line nr).

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks, I adjusted also those docs.

BTW, you like our **BaseModel** ? :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Didn't saw it yet. Idea is good tho!

**Comment by LuckyCyborg** [comment]
It is in **\App\Core\BaseModel**

And it is more advanced than the default one. :smirk: 

BTW, if you like to have an **insertBatch**, how about to have also an **updateBatch**  in your Engines? :smile: 

You are willing to write an **updateBatch** fast? :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Let me first open pull for more tests.

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, but I hope that you do not touch in you Tests our BaseModel, because its API is not yet well defined.

In theory, it is for offering an API compatible with our in-house Components, and my colleagues are not decided yet completely what they need to sports this BaseModel as API...

In other hand, I hope you will love something like:

```php

$data = $this->model
    ->where('color', 'black')
    ->limit(15, 0)
    ->fetchAll();
```

**Comment by tomvlk** [comment]
@LuckyCyborg But if you are not sure about the api, maybe a good idea for implementation in a later version? Or as a seperate component? 
Tests doesn't do anything with the basemodel.

**Comment by LuckyCyborg** [comment]
@tomvlk It is about days, as BaseModel's API decisions, do not worry, I have plenty of time... :smirk:  

In other hand, I'm almost successful in my deadline, and they can start to build things on top of Nova Framework, on January. In the mean time, I have time to adjust the BaseModel about their needs.

Yet, for Nova, it is a shiny and very useful add-on, yet, an add-on. 

Then, we will guarantee us that it will work right at the End of January, when Dave want Release, but it will work right on as we need...

**Comment by tomvlk** [comment]
@LuckyCyborg Then it's okay :dancers: .

**Comment by LuckyCyborg** [comment]
@tomvlk Yep. :smile:

**Comment by tomvlk** [comment]
@LuckyCyborg I'm not going to implement the batch update today, I will look into it tomorrow (evening) (if it isn't already done by then).

**Comment by tomvlk** [comment]
Btw, Some of your commits are in my pull request too, thats because it was needed, and the 3.0-beta was broken before that.

**Comment by LuckyCyborg** [comment]
@tomvlk In other hand, they asked for an updateBatch in BaseModel, then I need a similar method in Database Engines. And, I don't want to "enter" in your design, as introducing our style methods. 

That's why I asked you. Like you seen, we respected you Design, even if we introduced major changes in Engines...

**Comment by LuckyCyborg** [comment]
@tomvlk You talk about fixing Tests?

**Comment by tomvlk** [comment]
@LuckyCyborg Ye, the update batch is a good one, and I like it too. Going to implement that, but not today.
The 2 first commits in this pull request are in mine too: https://github.com/simple-mvc-framework/framework/pull/329.

**Comment by LuckyCyborg** [comment]
@tomvlk How that?

**Comment by tomvlk** [comment]
@LuckyCyborg Because it wasn't working, the 3.0-beta (before those 2 commits) was broken, and you did a fix here :laughing: .
And I applied the patch file from github, thats why it's showing your name, pushed with me :laughing: 
But it's no problem when merging!

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, then! :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, the Url::templatePath utility is questionable today... :smirk: 

Also, now templates can be customized per Controller.

AND, for a correct work of Routing Files Serving, there is need to use specific style paths, who are different from the real filesystem...

Then, I sugest you to not include it in tests.

**Comment by tomvlk** [comment]
@LuckyCyborg There are still some improvements for tests, and when it's going to be deleted just delete it from tests too. Please be gentle for the other tests.

**Comment by LuckyCyborg** [comment]
@tomvlk Okay. :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk There are the specifications wanted by my colleagues for future Engine's **updateBatch**

```php
/**
     * Updates multiple records in the database at once.
     *
     * $data = array(
     *     array(
     *         'title'  => 'My title',
     *         'body'   => 'body 1'
     *     ),
     *     array(
     *         'title'  => 'Another Title',
     *         'body'   => 'body 2'
     *     )
     * );
     *
     * The $where_key should be the name of the column to match the record on.
     * If $where_key == 'title', then each record would be matched on that
     * 'title' value of the array. This does mean that the array key needs
     * to be provided with each row's data.
     *
     * @param  string $table The Table name.
     * @param  array $data An associate array of row data to update.
     * @param  string $where The column name to match on.
     * @return bool
     */

$result = $this->db->updateBatch($this->table(), $data, $where);
```

**Comment by tomvlk** [comment]
@LuckyCyborg Thats exactly how I was thinking too ;)

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, then. Waiting, I implemented already our BaseModel part, with shiny before/after Events.

BTW, you know that our BaseModel is **Event** driven, and it have its own **Events Management**? Well, a much simple one, but exists as standalone. :smile:

**Pull request merged**
