### PR TITLE
autoDispatch when project not at root and parameters not as array

### PR DESCRIPTION
**Pull request by slamadeleine**
I removed the content of DIR from the path so that when the project is not at the root of the url, autoDispatch, will work.  I also changed the way the method is called so that the parameters are more in line with what the route does.  That way, instead of receiving an array as parameters, you actually receive every parameter.

### CODE REVIEW

**Comment by jimgwhit** [comment]
Has this been tested in all situations?

**Comment by slamadeleine** [comment]
I have tested it in all of my deployments with success.  (roughly a 
dozen sites)

Sébastien La Madeleine
B.Sc., M.Sc. Informatique
TooLSoft.ca
514-827-8665

**Comment by jimgwhit** [comment]
Has this been tested in both situations, and on PHP 7?  As of now framework works on PHP 7.

**Comment by jimgwhit** [comment]
But are all your projects set up the same way, you mentioned root., how about us who sets up the way the framework downloads?

**Comment by slamadeleine** [comment]
Yes it has been tested with both situation but not with php 7. Sorry I 
do not have this infrastructure in place yet.

Sébastien La Madeleine
B.Sc., M.Sc. Informatique
TooLSoft.ca
514-827-8665

**Comment by jimgwhit** [comment]
Please try to test that because as mentioned currently the framework is working on PHP 7 me and volter9 spent two days working all that out. Maybe Dave can test this on a PHP 7 version please do Dave.

**Comment by slamadeleine** [comment]
What I meant is that I have some sites in / and some sites in 
/site/something/else/ and these situations do work.  I do not understand 
your second question though...

Sébastien La Madeleine
B.Sc., M.Sc. Informatique
TooLSoft.ca
514-827-8665

**Comment by slamadeleine** [comment]
I can't right now, I'll try sometime next week...

**Comment by jimgwhit** [comment]
You said, I removed the content of DIR from the path, wouldn't the router still work with your alternate directory structure? And how did you remove dir?

**Comment by slamadeleine** [comment]
If you have a structure as such: 
/subfolder/controller/function/param1/param2

Auto dispatch would try to route to the controller "subfolder" with 
function "controller".  By removing the content of the DIR variable from 
the path, hopefully the DIR variable contains "/subfolder" or something 
similar, then autodispatch would route to the correct controller and 
function.  If you're using route, obviously this does not apply.

**Comment by jimgwhit** [comment]
There's something going on in current router that's not working on php 7, I made an issue, I hope @daveismyname figures it out.

**Comment by jimgwhit** [comment]
Ok, I tested on php 7.0.0RC1 your router, seems to work ok.  I am not a router expert, can you explain what the  
public static function autoDispatch() method does vs the public static function dispatch()?

**Comment by volter9** [comment]
> public static function autoDispatch() method does vs the public static function dispatch()?

dispatch() – dispatches manual added routes via magic methods `any`, `post`, `get`, etc.
autoDispatch() – dispatches routes that mapped to `App\Controllers` in CodeIgniter style

**Comment by jimgwhit** [comment]
Kinda like jream's original, right, it had no router? And glad to hear from you again @volter9

**Comment by jimgwhit** [comment]
That's to say no hard coded routes.

**Comment by slamadeleine** [comment]
The dispatch function uses the routes that you declared in routes.php.
AutoDispatch routes you to controller/function/param as some other framework.
On Oct 23, 2015 4:18 PM, jimgwhit <notifications@github.com> wrote:Ok, I tested on php 7.0.0RC1 your router, seems to work ok.  I am not a router expert, can you explain what the
public static function autoDispatch() method does vs the public static function dispatch()?

**Comment by slamadeleine** [comment]
Could not have said it better.
On Oct 23, 2015 4:20 PM, volter9 <notifications@github.com> wrote:
public static function autoDispatch() method does vs the public static function dispatch()?


dispatch() – dispatches manual added routes via magic methods any, post, get, etc.
autoDispatch() – dispatches routes that mapped to App\Controllers in CodeIgniter style

**Comment by jimgwhit** [comment]
@volter9 did you see my googup in issue #201?

**Comment by jimgwhit** [comment]
@slamadeleine thank's for your reply.

**Comment by jimgwhit** [comment]
Hey, where's Dave? I bet he's sleeping.

**Comment by daveismyname** [comment]
haha! not this time, I was setting up PHP 7.0.0RC5 on my local machine for anyone else looking for a dead simple way to test php 7 check out https://www.apachefriends.org/index.html

Now that's done I can look at this PR and test is on RC5 installed the FM all good so far!

**Comment by volter9** [comment]
> And glad to hear from you again @volter9

I'm watching this repo like

Watchman

> That's to say no hard coded routes.

**Comment by volter9** [comment]
> @volter9 did you see my goof up in issue #201?

Apparently, yes. That's happens to me sometimes, too. 

> haha! not this time

Hey, Dave! Once you mentioned your CMS based on SMVCF, can we see it? :sunglasses:

**Comment by daveismyname** [comment]
OK this is working with legacy calls as well as names routes on 7RC5.

@volter9 yes it's currently in a private repo so I'll just need to change that and remove a few unneeded things, bear in mind there is no documentation for it. I'll get a link sent across shortly.

**Comment by volter9** [comment]
> bear in mind there is no documentation

Don't worry about me, I'm learning through browsing source code, usually :wink:

**Comment by daveismyname** [comment]
OK here you go https://github.com/daveismynamecom/smvccms

I've updated the router so it works with php 7 happy hunting!, to install navigate to the files in terminal and run composer install then go to the project in a browser the page will auto redirect to the installer. The installer is deleted when done when on a live server only.

**Comment by volter9** [comment]
Thanks for sharing, I'll prepare for the wild hunt :sunglasses:

**Pull request merged**
