### PR TITLE
Multiple features & upgrades

### PR DESCRIPTION
**Pull request by ennerperez**
Uppercase folders in app folder
APPSTATE for offline/online environments
Separated routes from index
Language resx call style
Logger line fix for more readability
Include images in Assets
Included MSSQL for Windows Servers
Included plain text based GeoName

### CODE REVIEW

**Comment by andre2** [comment]
Why you remove author credits from all files?

**Comment by jimgwhit** [comment]
I feel this is too many changes at once, one file at at time, with no breaking code gives Dave more time to review and test. Look at issue  #174 where volter9 and myself made sure the router worked in all versions.  I feel one file at a time is great plenty here. There are those of us who have actual production databases in place, Dave included.  Any way to close this and do one pull request at a time? You need to leave any current credits.

**Comment by jimgwhit** [comment]
@volter9 is there an email address I can send you a private question? I need some help.

**Comment by volter9** [comment]
@jimgwhit, sure:
```php
$email = $my_github_nickname . 25 . '@gmail.com';

echo $email;
```

**Comment by volter9** [comment]
By the way, @ennerperez didn't removed the credits, he just added his name to any changes he made.

@ennerperez, you don't need to add your credits to all changes you made. Git keeps the information about changes you've made. Everyone who's browsing this git repository will know that those changes you've made.

**Comment by jimgwhit** [comment]
Dave if you implement these are you going to also do, Adjusted invokeObject method in router for PHP7
#175, It will have the framework work on the latest php 7.

**Comment by jimgwhit** [comment]
@volter9 said
~~~


lol, you should change this path in composer.json, not in the file itself :)

{
    /* ... */
    "autoload": {
        "psr-4": {"": "app/"},
        "files": ["app/files/password.php"] /* <- Here */
    },
    /* ... */
}


~~~
I don't think it's an external password library anymore, when ver 2.2 first came out, it was, but then it changed to the internal password file.

**Comment by volter9** [comment]
@jimgwhit even though you're right, It's really _useless_ to modify auto-generated file. What if Dave update the composer files via `composer update` or `composer dump-autoload` and commit it to the repository? The files would be *overwritten*.

**Comment by daveismyname** [comment]
First of all thanks for taking the time to contribute to this framework it's appreciated, as @jimgwhit has mentioned it would be better to do multiple pull requests for each change then they can be accepted/rejected on a per topic basis.

I'm going to reject this PR for the following reasons:

* Uppercase folders in app folder - only folders with classes in should be uppercase.
* this framework uses PRS 1,2 & 4 any code changes should meet the PSR 1 & 2 standards your PR does not, it needs to be modified to comply that way everyone is writing the same style.
* I don't like the socket connection been made on every page load, what's the benefit of setting APPSTATE?
* Never change anything inside the vendor folder as @volter9 has any changes made would be overwritten anytime composer update is ran on composer.json

Adding img to assets might be useful but it needs an alt tag in addition to the file path, it may make more sense to pass an array of options for the image to use so the method can use id, classes etc

The addition db class looks ok but needs to be written to support coding standards for instance rewritten as PSR:

````
try {
    if ($type == 'mssql' || $type == 'sqlsrv') {
        $instance = new Database("sqlsrv:Server=$host;Database=$name", $user, $pass);
    } else {
        $instance = new Database("$type:host=$host;dbname=$name;charset=utf8", $user, $pass);
    }
    $instance->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    // Setting Database into $instances to avoid duplication
    self::$instances[$id] = $instance;
    return $instance;
} catch (PDOException $e) {
    //in the event of an error record the error to ErrorLog.html
    Logger::newMessage($e);
    Logger::customErrorMsg();
}
````

Placing the routes in another file is an interesting idea that I'm not opposed to I think this should be discussed further to see what other think. If it were to be in a separate file then placing it in the files folder would make more sense then the root.

**Comment by ennerperez** [comment]
Sorry about my mistakes, I just make a pull with multiple suggestions in my particular use; I'll work more organized next time, thanks so much for all comments. I appreciate all explanations. @daveismyname I'll put in suggestions first. Nice to read you.

**Pull request closed without merging**
