### PR TITLE
Improve \Nova\ORM

### PR DESCRIPTION
**Pull request by LuckyCyborg**

### CODE REVIEW

**Comment by tomvlk** [comment]
Got inspired? :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk About what?

**Comment by tomvlk** [comment]
The solving structure.

**Comment by LuckyCyborg** [comment]
@tomvlk I used many solving structures on my history... :smirk: 

To be honest, I will implement this time, something similar with the style from **Laravel ORM** aka **Fluent**. Think that the relations are defined like:

```php
public function comments()
{
    return $this->hasMany('\App\Modules\Comment\Models\Comment', 'user_id');
}
```

Yet, I do not want to complicate the code too much... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk Maybe I will implement also **belongsToMany**, aka **ManyToMany**, also that Relation into Laravel style, aka with some **Pivot** associated methods like **attach()**, **dettach()** **sync()**.

Will be something like:

```
$pivot = $user->roles()->pivot();

$pivot->dettach($id);

$pivot->sync();
```

But is not yet decided, some of my colleagues wants it, others consider is a infantile complication. :smirk:

**Comment by tomvlk** [comment]
It's a complicated relation, maybe not for the simple orm in nova..

**Comment by LuckyCyborg** [comment]
@tomvlk Yep! You have to transparently handle the Pivot too. :smirk: 

And, like I said, the concept of Nova's ORM, as seen by us is as lightweight ORM, for small projects, ie. a small blog or simple backends.

It's a well defined niche. For other things, are plenty of options, including your own SweepORM.

**Comment by tomvlk** [comment]
Please make PizzaORM then :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk :laughing:

**Pull request merged**
