### PR TITLE
Make it possible to get services with the manager that belong to one …

### PR DESCRIPTION
**Pull request by tomvlk**
…of the modules. (absolute namespace service name).

Forgot this when making the manager save instances of Services and to use it for getting service instances.

It will now be possible to get services inside of a module by giving an absolute namespace class name to the Manager::getService($serviceName) service name parameter.
It's still possible to get a service with a relative namespace (just as it was).

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk Well, that much better. :+1: 

Yet, I have to ask you to be kind to follow a small convention: 

when we have a variable who contains a complete Class name, including its namespace, please use **$className**

This way, my colleagues can follow you easier... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk In other hand, I suggest you to use for checking the namespace/path, the following string : **App\Services**

**Comment by tomvlk** [comment]
@LuckyCyborg Will do that soon.

**Comment by LuckyCyborg** [comment]
@tomvlk and @daveismyname Okay, lets merge all pull-requests now, to initiate the moving of Database Demos into Demo Module!

**Comment by daveismyname** [comment]
this one needs updating before I can merge I should have merged this first.

**Comment by LuckyCyborg** [comment]
@daveismyname It about that both me and Tom we worked on same files. My #302 kicked this one out.

**Comment by tomvlk** [comment]
Im fixing it, has some merge conflicts. repairing now.. :dancer:

**Comment by tomvlk** [comment]
Done :dancer:

**Pull request merged**
