### PR TITLE
Added support for eloquent query builder skip take

### PR DESCRIPTION
**Pull request by jimgwhit**
Added methods for using query builders skip and take parameters.

### CODE REVIEW

**Comment by jimgwhit** [comment]
Done right this time.

**Comment by jimgwhit** [comment]
I did the first pull request (Added support for eloquent query builder skip take …) , then attempted the 2nd one, (Help page for eloquent skip take …) . But instead of create on my fork, only view pull request showed up. But it is listed above huh. But all code fixed.

**Comment by Volter9** [comment]
@jimgwhit just wonder, by Eloquent query builder you mean Laravel's query builder? If so, so it's an integration for Laravel's Eloquent?

**Comment by jimgwhit** [comment]
Yes

**Comment by jimgwhit** [comment]
From dave's video, it's called Laravel's Eloquent ORM, I am basically adding 2 methods to use skip and take parameters. I guess it's technically  illuminate/database.  That's from github.

**Comment by jimgwhit** [comment]
Anyone would still have to follow Dave's video for installing the illuminate database, I simply added an easier way to use the skip and take parameters.

**Comment by jimgwhit** [comment]
Dave you implemented my pull request #148, then nekomajim made some changes
in pull request 150 and 151. However I received no credit on the page for
paginator and the related help file page_eloq.md that shows the authors.
Can you please adjust it? The paginator skip take and page_eloq.md help
both were my original idea. Thanks.

**Comment by jimgwhit** [comment]
Dave you implemented my pull request #148, then nekomajim made some changes
in pull request 150 and 151. However I received no credit on the page for
paginator and the related help file page_eloq.md that shows the authors.
Can you please adjust it? The paginator skip take and page_eloq.md help
both were my original idea. Thanks.

**Comment by nekomajin** [comment]
@jimgwhit 
I'm sorry if it leaves a false impression. It was not my intention to show that the improvements were mine. I wanted to adjust the formatting. The gratitude you deserve.

**Comment by daveismyname** [comment]
sorry for the late response guys, I accepted your PR's github does not give me the ability to add or remove credit as far as I'm aware

**Comment by jimgwhit** [comment]
That's ok, at least it's in paginator now.  I use eloquent and the query builder in one of my production sites, and this is how I've been doing it a while now. Dave's method had the limit all together, which is fine for SMVC. But some folks probably want to use or try the illuminate database. Over all I like the database wrapper that's included with SMVC better.  But I just had to do one with illuminate database to see how it all works.

**Pull request merged**
