### PR TITLE
Multi engine dbal, support sqlite.

### PR DESCRIPTION
**Pull request by tomvlk**
Adding more functionality, factory instance management to the dbal (database services).

Better demo will come tonight with interactive code -> result examples.

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk  That Design of your Services implementation looks spectacular better! Congratulation!

**Comment by tomvlk** [comment]
@LuckyCyborg Thanks, let's get it ready, I will post a way more better example of using databases with and without the dbal tonight. Demo with code => result stuff
:christmas_tree: :santa: :gift:

**Comment by LuckyCyborg** [comment]
@tomvlk Yeah, Tom! Let's get it ready! :+1: 

With this pull-request of yours, I'm ensured that, deadline-d or not, we arrive to have an almost stable **Nova Framework** this Year, as in Release Candidate at minimum...  :smile:

**Comment by LuckyCyborg** [comment]
@tomvlk How about us to ask Dave to merge this pull-request, and you to open another one, when you are ready to complete the stuff and demos? :smirk:

**Pull request merged**
