### PR TITLE
[WIP] 3.0 update system/Language/de/messages.php

### PR DESCRIPTION
**Pull request by nekomajin**
@LuckyCyborg

*** **Do not Merge!** ***

Changes will be discussed. Followed by further commits.

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@nekomajin To note that the Language files used to be processed automatically with **/scripts/makelangs.php**, then make no sense to try to format them because at the first update, the formatting will vanish... :smirk:

**Comment by tomvlk** [comment]
@nekomajin Note on the current test results, Travis is having network issues so the builds will not succeed for now. Maybe later.
I will restart the test builds when failing later when the issues are fixed at Travis-CI.

**Comment by nekomajin** [comment]
@LuckyCyborg Ok, that should be all proposals. You can merge it when Travis CI also agrees :sweat_smile:

**Comment by LuckyCyborg** [comment]
@nekomajin Talking about latest patch, the space was intentional. But yeah, no problem, works this way, too...

Again, thanks for your all efforts, Martin! Bot for syntax fixes and the German translation! :+1:

**Pull request merged**
