### PR TITLE
3.0 - Lots of bugfixes!! And PHPDoc!!

### PR DESCRIPTION
**Pull request by tomvlk**
There we go, the big fix pull.

### Fixes and small improvements:
- Changed some stale SMVC to Nova
- Fixing syntax error in CacheManager
- Fixing missing import bug in CacheManager
- Fixing Logger sendEmail, was still using old PhpMailer syntax.

### PHPDocs
- Adding several phpdocs for a lot of methods
- Can still be not correct, if not please correct me after this pull request. I can't be accurate for 100%.
- Untouched: The Nova Small ORM (still in building phase), Helpers, Input and Validator (needs more checking)

## Important note on \Nova\Database\Connection (Unstable!)
There is a bug in the Connection.php, it's been marked as unstable in the phpdoc and marked with TODO at the line of the bug.
@LuckyCyborg Please look into this, I don't know exactly what you wanted to do in this line so I didn't fix it. Please open pull to fix later.

## Doc opinions
Maybe the doc style I use here isn't your style. Please discuss and open pull if agreed, or leave as it is. I won't change it in this pull.

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk Thanks for finding the bug about the experiment of my colleague Mario, who proposed (me) to implement an OR for WHERE conditions. 

I don't finished that integration and I even decided yet if I keep it or not. Whatever, the thing have no impact to \Nova\Database\Connection functionality and a know stage of work.

So, please stop acting like you discovered the Wheel! 

In other hand, probably you are introduced a bug in the Nova\Cache\Manager, because that:

```php
use \phpFastCache;
```

This about using **a Class** with no namespace, similar with **\PDO**, for example. So probably will not work.

Please stop considering you know everything and ask when are, or you consider, questionable things. 

BTW, with all the respect, I do not care even you mark my entire code as alpha-beta-zetta in you PHPDOC, which I'm happy to ignore...

All the best!

**Comment by tomvlk** [comment]
@LuckyCyborg Thanks for your support... Again..
Thanks for helping out, thanks thanks thanks. Bullshit... You asked for it.. :trollface:. Don't point to your colleagues, it's not about that, it's about the code quality.
keep it simple stupid.

I strongly advice to implement PHPDoc everywere. PHPDoc will help determinate the required types, give help popups when working in **IDEs** and the smart **Editors** nowadays. And can be generating a document of classes.

**Comment by LuckyCyborg** [comment]
@tomvlk Tom, you think that you discovered America? I leaved **intentionally** in this way, to disable the sequence, not being yet decided about its utility.

Look how it works, first to talk.

BTW, from when I have to rapport to you my intentions?

And please stop messing with code which you do not understand! You discovered a small bug, which literally do nothing, but probably introduced another one! Nice!

**Comment by tomvlk** [comment]
@LuckyCyborg Please think and test before implementing, this means you have code thats unused, and old. Hmm **Code Smells** :nose:

**Comment by LuckyCyborg** [comment]
@tomvlk Tom, what you understand when you say "you have code thats unused, and old. Hmm Code Smells" ?

Eventually your code smells. When i implemented the Database Wrapper for your ORM, I presented your ORM for a common analysis to see what it needs. And we laugh with tears! Thanks for that day!

**Comment by tomvlk** [comment]
@LuckyCyborg Can't stop laughing about this reaction of yours... Some of us will. But those will understand... :trollface:

**Comment by LuckyCyborg** [comment]
@tomvlk In other hand, right now I tested internally the **CacheManager**... Guess what?

You fixed a bug so insignifiant that was not visible on tests, because introduce a never used entry, but YOU introduced a nice bug and Cache stopped working. Guess what?

It no known where is the Class **phpFastCache**!

Nice, Tom! :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Not about tests lol. Don't say something you don't know. It wasn't imported. 
So? Fix? :trollface: :laughing: ..

**Comment by LuckyCyborg** [comment]
@tomvlk Tom, what you want to demonstrate?

Me, probably I demonstrated that I know enough how works an functional and advanced MVC Framework to write one. But that was supposed to be capable.

 You, what you want to demonstrate?

**Comment by tomvlk** [comment]
@LuckyCyborg What you mean?

**Comment by LuckyCyborg** [comment]
@tomvlk What you mean with this Scandal Newspaper like title: **Lots of bugfixes!!**

And I talking about this bullshit: **Important note on \Nova\Database\Connection (Unstable!)**

After all, sure you are capable to understand how that code sequence work?

And where you seen lots of bugs? What you are smoke man?

**Comment by tomvlk** [comment]
I live in the Netherlands so guess what...... :laughing: 
It was a bit too much of the **Lots of fixes** maybe..

**Pull request merged**
