### PR TITLE
Better Form

### PR DESCRIPTION
**Pull request by BryanYeh**
Helpers\Form.php, I have changed completey
Some examples of the form and inputs are in the welcome.php
Ignore the changes in the config.example.php or config.php

-if plan to use it, i suggest fixing it up a bit in case my code isn't as good

### CODE REVIEW

**Comment by geomorillo** [comment]
Why the deletion of  app/Core/Config.example.php ?

**Comment by BryanYeh** [comment]
I renamed the config.example to config. i didn't change it back.

**Comment by jimgwhit** [comment]
Are you going to name it back?

**Comment by jimgwhit** [comment]
Wouldn't it be better if you got everything all squared away first correctly then did a pull request instead of four request to accomplish the same thing?

**Comment by BryanYeh** [comment]
I've never done a pull request before, I just commited my files seperately and pushed to my repo, then I did a pull request. So I'm not sure myself.

**Comment by BryanYeh** [comment]
I'll just close do a new pull request later in the day.

**Comment by jimgwhit** [comment]
What you could do is now delete your repo do a re fork and start all over, that's what I had to do once, it was just easier just to do a re fork. But hey we all have to learn from scratch at one time or the other. You could try to make upstream override your master it may work. Don't forget to backup your current changes first in another folder.

**Pull request closed without merging**
