### PR TITLE
3.0 add german language in system/Language/de/messages.php

### PR DESCRIPTION
**Pull request by nekomajin**
**Not merge yet!**
Please check the translations and make improvements.

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@nekomajin Good Job, smart German guy!

There is a small bug in the Language Updater, who eat **)**, fixed in my current pull request.

YET, you made the corrections and got the right strings, as they will be after merging my current work. Congratulation!

**Comment by geomorillo** [comment]
Lol i noticed it but translate it with the "bug" sorry.

**Comment by LuckyCyborg** [comment]
@geomorillo Then, my Spanish friend, maybe you want to adjust the Spanish file? Also you have some new string to translate.

**Comment by LuckyCyborg** [comment]
@geomorillo Looks like you translated right, just like our German friend.

```
'The :field field may only contain alpha characters (a-z).' => 'El campo :field solo puedo contener caracteres alfabéticos (a-z).',
```

**Pull request merged**
