### PR TITLE
3.0 - Final Phase, stage continued #15

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Making the Database Services better citizens while auto-configuring the Engine's Fetch Method

### CODE REVIEW

**Comment by tomvlk** [comment]
Ehm. Services should always do a fetch class! With the entity as a class. This is incorrect

**Comment by LuckyCyborg** [comment]
@tomvlk If I'm so wrong **why** this code pass your "tests" and the Database Demos works?

**Comment by tomvlk** [comment]
Because the service tests are still not done in the 3.0-beta on here.

**Comment by LuckyCyborg** [comment]
@tomvlk Sure, **BUT** why the Database Service Demos works?

**Comment by tomvlk** [comment]
Because a class is also an object v.v. Demo doesn't uses entity itself, and is not checking it its instance of the entity. 
But when you are going to declare function in your entity and try to use it it doesn't work. 

Why not object? Entity can have functions like getName() that will concatenate first name with last name for example.

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, then also your Demos are incomplete. I understand. :smirk:

**Comment by tomvlk** [comment]
Not directly incomplete. But there can be a toString for example that will provide a string notation for the car. 
But that's fully optional. Would be good in the demo I think.

**Comment by LuckyCyborg** [comment]
@tomvlk I believe that would be better to have it in Demos.

**Comment by tomvlk** [comment]
Ye. I can't do it right now. But will add it.

**Pull request merged**
