### PR TITLE
View class refactoring

### PR DESCRIPTION
**Pull request by volter9**
Could somebody check if everything works correct (just in case)?

### CODE REVIEW

**Comment by jimgwhit** [comment]
I caught this too late at night to test on php 7 it's bed time, so @daveismyname test this not once, not twice, but at least 3 times. And then once more.

**Comment by volter9** [comment]
@jimgwhit nice to see sticking around :smile:

**Comment by jimgwhit** [comment]
@volter9 do you know when php 7 final not an RC will be out?

**Comment by volter9** [comment]
@jimgwhit not really sure, I thought it would be released on Nov 20-something

**Comment by Kingorgg** [comment]
@jimgwhit November 26th, maybe.

https://wiki.php.net/todo/php70#timetable

**Comment by Kingorgg** [comment]
Oh and, the changes you made @volter9 works fine on my end.

**Comment by volter9** [comment]
@Kingorgg thanks for checking, I just needed to be sure that everything works fine.

**Comment by nekomajin** [comment]
@volter9 very good change. All things work good :+1:

**Comment by jimgwhit** [comment]
Please make sure it works on PHP 7 as well Thanks.

**Comment by volter9** [comment]
Thanks guys for testing :)

@jimgwhit I don't think that this PR should break something, it's just a class refactoring.

**Comment by jimgwhit** [comment]
@volter9  why the change?

**Comment by Kingorgg** [comment]
@jimgwhit  From what I can see, it now follows DRY (Don't 
Repeat Yourself) Which is useful if you want to edit the class in the future.

**Comment by geomorillo** [comment]
+1

**Comment by volter9** [comment]
@jimgwhit @Kingorgg pointed out the reason. Code duplication isn't right, especially in more than 2 places in the same class :)

@geomorillo thanks :)

**Comment by daveismyname** [comment]
All working on 7.0.0RC7 too.

**Pull request merged**
