### PR TITLE
added key generation method to data helper class

### PR DESCRIPTION
**Pull request by baruchvlz**
I found this to be useful when used with user registration and confirm registration emails.

### CODE REVIEW

**Comment by jimgwhit** [comment]
Does this also work in PHP 7 I ask because as of now the framework is completely PHP 7 compatible and just need to keep it that way?

**Comment by jimgwhit** [comment]
Speaking of which Dave will you be making sure that any future pull request is PHP 7 compatible and backwards compatible to PHP 5.5?

**Comment by baruchvlz** [comment]
I haven't tried it in PHP 7. I honestly haven't read the changes in PHP 7.

**Comment by jimgwhit** [comment]
You said this is for user registration however password is already built into the framework so where and why would you use it just curious.

**Comment by baruchvlz** [comment]
I've used it for database relation keys, confirm email links, and unique keys in rows. I don't like using the a_i id as a way to fetch information from database so I use this to generate a unique key to every user, message, page, comment, post, etc.

**Comment by geomorillo** [comment]
i think we already have a 32 char string generator the method is on Csrf helper
class Csrf {

    public static function makeToken() {
        $csrf_token = md5(uniqid(rand(), TRUE));
        return $csrf_token;
    }

}

**Comment by baruchvlz** [comment]
What version of the framework is that method in? V2.2 makeToken method is different.

```
    public static function makeToken()
    {
        $max_time    = 60 * 60 * 24; // token is valid for 1 day
        $csrf_token = Session::get('csrf_token');
        $stored_time  = Session::get('csrf_token_time');

        if ($max_time + $stored_time <= time() || empty($csrf_token)) {
            Session::set('csrf_token', md5(uniqid(rand(), true)));
            Session::set('csrf_token_time', time());
        }

        return Session::get('csrf_token');
    }
```

**Comment by geomorillo** [comment]
eh you are right maybe this was a previous version sorry.

**Comment by geomorillo** [comment]
I wonder wich one is better 
``` str_shuffle(md5("!@#$%^&*)_+-=0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHJIKLMNOPQRSTUVWXYZ")); ```
or
```  md5(uniqid(rand(), TRUE)); ```

**Comment by baruchvlz** [comment]
Either one works fine. They will both create a 32 char string, so its up to preference.

**Comment by geomorillo** [comment]
also it would be usefull if you could set the string length
```
function randomkey($length = 32) {
        $chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890";
        $key = "";

        for ($i = 0; $i < $length; $i++) {
            $key .= $chars{rand(0, strlen($chars) - 1)};
        }

        return $key;
    }
```

**Comment by baruchvlz** [comment]
+1 
That's a great idea.

Changed the contribution

**Comment by daveismyname** [comment]
thanks really useful!.

**Pull request merged**
