### PR TITLE
Cleanup, bug squashing (with love), phpdoc fixes, code smell (done)

### PR DESCRIPTION
**Pull request by tomvlk**
Lots of bug fixes.
Cleanup of unused (local) variables, imports, etc,etc
Improved and fixed PHPDoc, types, throws, returning types, parameters etc etc.
Code Smell :nose:, improved returning types, so it does really return that type you asked for :wink: 

So, overall fixing pull. Must be tested! I already tried to test somethings but please test with me.

### CODE REVIEW

**Comment by tomvlk** [comment]
The last commit really needs full testing, every bit of the framework. I automaticly reformatted every bit of the Nova code. We could revert if there are any problems of course!

**Comment by LuckyCyborg** [comment]
@tomvlk And another thing, do not try to reformat the Language files; there is an Language Updater script who will kill your shiny formatting at first use by me or Dave.

**Comment by tomvlk** [comment]
@LuckyCyborg I reverted the reformat, I will selectively reformat files that are only classes and no customizable stuff. It was a bit too much reformatting :laughing: even the minified jquery was reformatted.
I will open another pull when doing reformat, but that later.

**Comment by LuckyCyborg** [comment]
@tomvlk Do not touch the classes where I work!

**Comment by tomvlk** [comment]
@LuckyCyborg wait. it's github!

**Comment by LuckyCyborg** [comment]
@tomvlk You can touch them all you want after I finish my work with them. :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, you know what return by default a PHP function, when you don't specify a value? **NULL**

Why try to return **null**? Just curious.

**Comment by LuckyCyborg** [comment]
@tomvlk 
```php
public static function getSegment($segments, $id)
    {
        if (array_key_exists($id, $segments)) {
            return $segments[$id];
        }
    }
```
is similar with:

```php
public static function getSegment($segments, $id)
    {
        if (array_key_exists($id, $segments)) {
            return $segments[$id];
        }
        return null;
    }
```

Where you want to return **''**, which is not equivalent with null. And WHAT IF somewhere check the presence of NULL, to conclude about no segments?

Also, there is NO segment with value '', or it have a value, or it is NULL.

**Comment by tomvlk** [comment]
Should be changed. Tomorrow.

**Comment by LuckyCyborg** [comment]
@tomvlk OK, Tom! Yuu are right, is too late in the night, now. :smile:

**Comment by tomvlk** [comment]
@LuckyCyborg I always learned myself, if I return something in a if within function, also return when it's not the case (after the if). No matter what return it is, (null or something else). But just so you can see in the code more clearny that something is going to be returned.

**Comment by LuckyCyborg** [comment]
@tomvlk OK, Tom. Let's talk about some things about clearny writen code:

I don't know you, but us we have habit to use the **use** as a short indication about WHAT classes are used. There are more people who look in this code, beyond Dave, me and you. Are my colleagues. And they have the habit to look to uses, to understand what classes are currently used. 

So, you are very gentle to not "simplify" the **USE** ?

**Comment by LuckyCyborg** [comment]
@tomvlk It is a very bad idea to apply auto-formatting over **hot** code, the on code where someone curently work.

**Comment by LuckyCyborg** [comment]
@tomvlk Also, WHEN you introduce changes in behavior, as in returning, this changes should be discussed well first. Capisci?

**Comment by LuckyCyborg** [comment]
@tomvlk Also, we believe being more clean to do:

```
if(! $crap) {
    echo "That's good!";
}
```

Notice the space after **negation**!

**Comment by tomvlk** [comment]
It's all about style you like or you follow, I didn't change most of the styles (after the revert has been done).

**Comment by LuckyCyborg** [comment]
@tomvlk Tom, I work in a team of 11. Sure there are style rules to follow, and I write code readable not only by you and me, but also by my colleagues.

And I repeat, **please, let's discuss every returning change, in detail**, before to modify them. Playing with returning values is the best mode to make an application to go nuts! Trust me!

**Comment by tomvlk** [comment]
What statement? the returning empty string?

**Comment by LuckyCyborg** [comment]
On statement of function or method. I noticed one of introducing questionable behavior, in that Url method, I have't time to think on all your changes. So, how about to dump a function there and to discuss it?

**Comment by LuckyCyborg** [comment]
@tomvlk For example, that is wrong, changing is behavior and introducing changes in post-processing of return value:

```php
    public static function getSegment($segments, $id)
    {
        if (array_key_exists($id, $segments)) {
            return $segments[$id];
        }
        return '';
    }
```

That function should return a non-empty string or NULL.

**Comment by tomvlk** [comment]
That one is reverted

**Comment by LuckyCyborg** [comment]
@tomvlk That's one what I spotted, maybe there are another ones? 

And talking about the questionable behavior, please do something about your (multi-)**insert**. Need a special post-processing of return values, imcopatible with plug&play on existent code. I suggest you to revert to classic on insert and eventually write a multi-insert, as you like, called how you wish, insertMulti, insertMultiple, multiInsert,, etc.

**Comment by LuckyCyborg** [comment]
@tomvlk Also, look at my current work, aka pull-request. For example, I nuked **Nova\Helpers\Hooks**.

Its services are now offered by Events Management, and I could say that is stalled code, who drive nuts the Controllers, today.

**Comment by tomvlk** [comment]
@LuckyCyborg The behavoir of the insert without using multi insert is exactly the same as before!

**Comment by LuckyCyborg** [comment]
@tomvlk And if you have a multi-insert and a single one is successfully?

Still, you don't expect "insert" to return arrays. ;)

**Comment by LuckyCyborg** [comment]
@tomvlk On \Nova\Core\Model

public function __construct($connectionName = 'default')

Descriptive variable name, but how about one more short, ie $connName

**Comment by LuckyCyborg** [comment]
@tomvlk Another sugestion:

How about to move **\Nova\Helpers\TableBuilder** on **\Nova\Database** namespace?

**Comment by LuckyCyborg** [comment]
@tomvlk Ha! You commented my $expires in \Nova\Net\Response !

While, if you look right on my current pull request, you see that IT IS USED. If your pull-request in accepted after one from me, you introduce questionable behavior again!

**Comment by LuckyCyborg** [comment]
@tomvlk Again, I see that you love to kill the space after our negations in IFs & Co...

Look, we are used to write:

```php
while (! empty($parts)) {
```

That's NOT A TYPPO! Literally I want to write this way the sequence! OK?

And I ask you to be kind to make those sequences to remain this way!

**Comment by tomvlk** [comment]
@LuckyCyborg Which commit? I didn't do that myself. Sorry but must be some auto formatting stuff. Wasn't it reverted later on?

**Comment by LuckyCyborg** [comment]
@tomvlk Don't know, I look in PR files changes.

**Comment by LuckyCyborg** [comment]
@tomvlk Funny, while you kill the spaces after negations, also, you introduce TWO space for every frakking string collation, aka ' . '...

Oh, man! :-1:

**Comment by LuckyCyborg** [comment]
@tomvlk And finally, look like both of us patches the \App\Core\ClassicRouter for SMVC stall thingie.

**Comment by LuckyCyborg** [comment]
@tomvlk Nice! You spotted a typpo in our **Validator**, thank you!

```php
$retval[$field] = filter_var($data[$fields], FILTER_SANITIZE_STRING);
```

**Comment by LuckyCyborg** [comment]
@tomvlk AGAIN: DO not comment **$expires** on **system/Net/Response.php**

**Comment by LuckyCyborg** [comment]
@tomvlk system/Net/Session.php

Spotted another returning value behavior change. It is supposed to return non-empty string or NULL, NOT ''.

**Comment by tomvlk** [comment]
@LuckyCyborg Just reverted, and the php concatenation operator needs spaces before and after it because it makes it more readable.

**Comment by LuckyCyborg** [comment]
@tomvlk We use space before only, considering that's enough. Or no space at all, for compact commands. If you really wish spaces, use, please, one space before, and nop one after. 

Please revert all your changes, in \App\Core\ClassicRouter.

I don't want to see it in your files change right now, because I work there also I! OK? 

I

**Comment by LuckyCyborg** [comment]
@tomvlk In View::renderModule
```php
if(is_array($data)) {
```
WHY, if the default value is boolean false?

**Comment by tomvlk** [comment]
@LuckyCyborg Because it will check types, and it's better to check if array. If you don't you can even put true in it and will cause several errors, or will render with errors without the developer will know.

**Comment by LuckyCyborg** [comment]
@tomvlk Also, IN MY PR, I introduce some huge changes on Data processing in \Nova\Core\View.

**Comment by tomvlk** [comment]
@LuckyCyborg then we merge it :+1:

**Comment by LuckyCyborg** [comment]
@tomvlk Again, look at my PR, to see how it look now \Nova\Core\View

**Comment by LuckyCyborg** [comment]
@tomvlk Please revert:

```
@@ -388,7 +408,7 @@ public static function renderLayout($layout, $content, $data = false, $custom =
             throw new \UnexpectedValueException('File not found: '.$filePath);
         }
 
-        if($data) {
+        if(is_array($data)) {
             // Extract the rendering variables.
             foreach($data as $name => $value) {
                 ${$name} = $value;
```
Make no sense, while I changed already the data processing in this method, in my current tree.

**Comment by tomvlk** [comment]
@LuckyCyborg Ok.

**Comment by LuckyCyborg** [comment]
@tomvlk You want to do cool things?

Instead of:

```php
foreach ($error as $err) {
foreach ($where as $wher) {
```

please use:


```php
foreach ($error as $what) {
foreach ($where as $what) {
```

**Comment by LuckyCyborg** [comment]
@tomvlk  And find a more short name for variable in:

```
@@ -26,10 +26,12 @@
 
     /**
      * Create a new instance of the database helper.
+     *
+     * @param string $connectionName Custom connection name, default is 'default'
      */
-    public function __construct()
+    public function __construct($connectionName = 'default')
     {
         /** connect to PDO here. */
-        $this->db = Database::get();
+        $this->db = Manager::getEngine($connectionName);
     }
 }
``` 

How about $connName or whatever?

**Comment by tomvlk** [comment]
@LuckyCyborg $connectionName is used multiple times in the whole database part, so it's better to stick with the same name.

**Comment by LuckyCyborg** [comment]
@tomvlk Then change in all Database! :smirk: 

It is soo long.

BTW, you are Spanish?

**Comment by LuckyCyborg** [comment]
@tomvlk And PLEASE, do not TOUCH **\NOVA\HELPERS\HOOKS**,

This class will be deleted by my pull-request.

**Comment by tomvlk** [comment]
@LuckyCyborg connectionName isn't that bad, not too long. And not spanish. 
The hooks will be removed once this pull has been merged before yours. And if it doesn't we will fix it later.
I need to focus on some work now...

**Comment by geomorillo** [comment]
i really don't like short non descriptive variables, since my native language is Spanish 'connName' doesn't mean nothing to me, please think of others developers, yes we all speak English here but we also like to collaborate in the future fixing bugs, also i thing 'connectionName' is a good name not too long, descriptive enough, if you are find tiring writing long variable names then use a better ide with autocompletion, they can help a lot.

**Comment by LuckyCyborg** [comment]
@geomorillo Permit me to doubt we have same opinion about what is "short name", considering that I known well that the Spanish have their own very personal style in things and people naming...

How about, **linkName**

**connection <-> link**

**Comment by geomorillo** [comment]
:+1:

**Comment by daveismyname** [comment]
> I nuked Nova\Helpers\Hooks

Late to this conversation, getting hard to keep up with everything. 

I use hooks extensively on our internal CRM system each section comes directly from hooks, if there is not hooks how would modules "hook" themselves into the various parts of the framework.

Can you give a syntax example? I'd rather not have to rebuild my entire modules to work with 3.0

Please DON'T DELETE EXISTING CLASSES without speaking with me, we need to discuss such drastic changes. The extra's your building in is meant to be optional. 

 Also I've noticed the database use statement has been removed from the tags helper, going forward how will that helper be able to use database calls internally?

**Comment by tomvlk** [comment]
@daveismyname The tags helper isn't using the database right now as far and fast I can see right now.
Once I get back the hook helper, would it be possible to merge this pull?

**Comment by daveismyname** [comment]
Ah yes sorry I'm playing catchup, it's in the other PR from @LuckyCyborg with regard to the tags helper you're right it's on my live version where I have a query going on. 

I don't have any queries in the download version so it's entirely optional if a database is used or not. This is not a big deal is can be added in on a as needed basis from the end user.

**Comment by LuckyCyborg** [comment]
@daveismyname 

> I use hooks extensively on our internal CRM system each section comes directly from hooks, if there > is not hooks how would modules "hook" themselves into the various parts of the framework.

Then you'll love the new **Events Management** who permit much powerful communication between components, and of course, Modules, even executing a Controller from a Module right on its properly Views Context. 

Worry not, I want to "steal" your Mini and leave on your hands the keys from a Rolls-Royce.

> Can you give a syntax example? I'd rather not have to rebuild my entire modules to work with 3.0

I have a complete functional example on my current pull-request on using the Events to request data from another Classes or even Live Controllers.

**Pull request merged**
