### PR TITLE
3.0 - ORM Continued..

### PR DESCRIPTION
**Pull request by tomvlk**
Adding the following:
- Query building for Entity finding
- Complete find methods
- Refactor + cleanup tests, entity etc.

How to fetch entities, all the styles:
```php
$one = Car::find(1); // Find by primary key value
$one = Car::findBy('model', 'Model S'); // Find by simple = compare
$one = Car::findBy('model', '<>', 'Model S'); // Find by simple custom operator compare
$multiple = Car::findMany(array(1, 2)); // Find multiple cars with array of primary key values.

// Custom queries
$one = Car::find()->where('model', 'Model S')->one(); // Fetch a single Car with where condition
$one = Car::query()->where('model', 'Model S')->one(); // Exactly the same, you can start the query with 2 methods

$all = Car::find()->where('make', 'IN', array('Tesla', 'BMW'))->all(); // Get all entities with where condition, IN condition.
$all = Car::find()->limit(50)->offset(100)->all(); // Get 50 cars, starting by record 100.

// Just get all cars from database:
$all = Car::find()->all();
```

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk See that wasn't difficult to implement that? You arrive to common sense? 

I talk about that:

```php
$one = Car::findBy('model', 'Model S'); 
```

BTW, if you want a smart suggestion:

use **getOne** and **getAll**, because sound better.

**Comment by tomvlk** [comment]
@LuckyCyborg That one is good right :rocket: 
Getone and all for the Query building stuff or for the findBy?

**Comment by LuckyCyborg** [comment]
@tomvlk I talk about your Query builder methods.

BTW, what's your arguments to build a custom QueryBuilder for ORM?

**Comment by tomvlk** [comment]
@LuckyCyborg The $_state injection, not having to write sql, and column validation.

**Comment by LuckyCyborg** [comment]
@tomvlk Good enough! :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Errors:
Database/Connection: Line 140, if(! class_exists($fetchType)) {, $fetchType undefined

**Comment by LuckyCyborg** [comment]
@tomvlk I will look right now! Thanks for report!

**Comment by LuckyCyborg** [comment]
@tomvlk Should be now fixed.

**Comment by tomvlk** [comment]
@LuckyCyborg Still something really wrong with fetching class in the connection..

**Comment by tomvlk** [comment]
@LuckyCyborg Please wait before the tests are finished, you can look at the error logs here:
https://travis-ci.org/tomvlk/php-framework/jobs/101240058

**Comment by tomvlk** [comment]
@LuckyCyborg I did a breakpoint in the fetch type and this is the fetch type returned from your ```getFetchMethod```:

The memory when breaking at Connection.php line 338:
```
$className = null
$fetchAll = true
$fetchMethod = 8
$paramTypes = {array} [1]
$params = {array} [1]
$returnType = "App\Modules\Demo\Models\Entities\Car"
$sql = "SELECT * FROM smvc_car WHERE carid IN (?)"
```

**Comment by tomvlk** [comment]
@LuckyCyborg Extended:

```
$paramTypes = {array} [1]
     0 = 1
$params = {array} [1]
     0 = 1
```

**Comment by LuckyCyborg** [comment]
@tomvlk I will look into 30-45 minutes to that problem. 

Right now, we have a Briefing, sorry for delay!

**Comment by tomvlk** [comment]
Ok, no problem, I have some problems here too, and will prepare the relation in my head full of ideas :laughing: :+1:

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, also, please commit your work as is it now, to have a look into, and eventually fix something.

**Comment by tomvlk** [comment]
I did, you want me to merge it into 3.0-beta here?

**Comment by LuckyCyborg** [comment]
@tomvlk Yep, that's idea.

**Comment by tomvlk** [comment]
@LuckyCyborg Done

**Comment by LuckyCyborg** [comment]
@tomvlk  Oh, a difference between Doctrine DBAL and Nova DBAL are the parameters binding, as into Nova DBAL they are named:

Like:

```php
$params = array(
    'username' => 'admin',
    'email' => 'admin@novaframwork.dev'
} 
```

Also, the **$paramTypes** are named:

```php
$paramTypes = array(
    'username' => PDO::PARAM_STR,
    'email' => PDO::PARAM_STR
} 
```

Hope it help! :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Aha, but why not make it like it also is in PDO? Also numbers, because the numbers are very light to implement, and very good when using a building on the where.

**Comment by LuckyCyborg** [comment]
@tomvlk To simplify the things.

**Comment by LuckyCyborg** [comment]
@tomvlk Practically, if there is not defined a parameter type into $paramTypes, the Connection try to guess its type.

**Comment by LuckyCyborg** [comment]
@tomvlk Another fix into **\Nova\Database\Connection**, please update your fork. 

Now Connection should work as supposed by us.

**Comment by tomvlk** [comment]
@LuckyCyborg I added support for question mark binding.
Btw, another error:
```php
return $stmt->fetch($fetchMethod, $className);
```
Is invalid, you can't give the className as second parameter!

**Comment by LuckyCyborg** [comment]
@tomvlk The fail was with you with that "fix"... :-1: 

Please revert that "fix"!

**Comment by tomvlk** [comment]
@LuckyCyborg Still the single fetch isn't working, you can't give the second parameter for class.

**Comment by tomvlk** [comment]
@LuckyCyborg Fixed!

**Comment by LuckyCyborg** [comment]
@tomvlk You talk about what **fetch** ?

That returned by **QueryBuilder** or by **Connection** itself ?

**Comment by tomvlk** [comment]
Look at last commit in my fork, you will see.

**Comment by tomvlk** [comment]
@LuckyCyborg And its merged.

**Comment by LuckyCyborg** [comment]
@tomvlk And you should revert it, again. 

Understand that there is a **PDOStatement** not a Doctrine DBAL's **Statement**.

**Comment by LuckyCyborg** [comment]
And do not touch **Nova\Database\Connection**, please!

You should adapt **your ORM** to it, **not** it to ORM!

**Comment by tomvlk** [comment]
@LuckyCyborg I think you should look a bit better. It's the original Engine, the new nova dbal what I'm working on :trollface: and I know that.

**Comment by tomvlk** [comment]
@LuckyCyborg Please mister Adrian, the Connection is the old engine, And I will touch it again for fixing a lot of bugs and phpdocs in few minutes.

**Comment by LuckyCyborg** [comment]
@tomvlk And I kindly remember you that you should adapt your ORM to this API, without to add changes to **\Nova\Database**.

I consider this **\Nova\Database** bug free, now.

If your ORM can't work with it, without including modifications, you can keep it into Doctrine based DBAL, using a **Package**.

**Comment by tomvlk** [comment]
@LuckyCyborg It's about performance, the question mark is a must for ORM. Sorry.

**Comment by tomvlk** [comment]
@LuckyCyborg Already found bug :trollface:

**Comment by LuckyCyborg** [comment]
Then go Package with it and we finish this!

**Comment by tomvlk** [comment]
@LuckyCyborg I think I will make my own Nova framework if you continue by pulling the framework to your framework.
You should not act as a frustrating italian maffia boss here! Please consider accepting changes to the Connection, it's not your project.

**Comment by tomvlk** [comment]
Can I ask you why you didn't revert the whole engine structure at first? That was a gold, good and stable structure!

**Comment by LuckyCyborg** [comment]
@tomvlk Look into code and you will see that the bindParam should be index safe to use numeric bindings.

Because it can be called several times in a single method. That's why your commit is Fail. You do not resolved the unique index.

If you can't understand this, then step back, drink a beer and calm down.

**Comment by tomvlk** [comment]
@LuckyCyborg Then fix it on your way please, captain Connection.

**Comment by LuckyCyborg** [comment]
@tomvlk We do not need the **bindParams** to do numeric indexes binding, just to avoid the said complications.

To keep the code simple.

That's why we made it in this way.

**Comment by tomvlk** [comment]
@LuckyCyborg You should add it or the ORM will be removed, simple as hell.

**Comment by LuckyCyborg** [comment]
@tomvlk Consider that we consider the ORM as your Pet Project, right now. 

We support you as best as we can, but if you want and need those numeric indexes, please come with a valid solution!

**Comment by tomvlk** [comment]
Who are the **we** you are using always btw?
I will abandon the ORM in Nova I think, will make my own, not including into your company framework.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Who are the we you are using always btw?

Those who written around of 90% of code from **Nova Framework**, if I remember right.

> I will abandon the ORM in Nova I think, will make my own, not including into your company framework.

Tom, **if you are so vainglorious** that you can't understand when your patch introduce strange collateral bugs,  then we have a big problem with... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk I talk about that:

```diff
@@ -177,29 +177,24 @@ public function bindParams($statement, array $params, array $paramTypes = array(
 
         // Bind the key and values (only if given).
         foreach ($params as $key => $value) {
-            $bindKey = $prefix .$key;
-            if (is_int($key)) {
-                $bindKey = $key+1;
-            }
-
             if(isset($paramTypes[$key])) {
-                $statement->bindValue($bindKey, $value, $paramTypes[$key]);
+                $statement->bindValue($prefix .$key, $value, $paramTypes[$key]);
 
                 continue;
             }
 
             // No parameter Type found, we try our best of to guess it.
             if (is_integer($value)) {
-                $statement->bindValue($bindKey, $value, PDO::PARAM_INT);
+                $statement->bindValue($prefix .$key, $value, PDO::PARAM_INT);
             }
             else if (is_bool($value)) {
-                $statement->bindValue($bindKey, $value, PDO::PARAM_BOOL);
+                $statement->bindValue($prefix .$key, $value, PDO::PARAM_BOOL);
             }
             else if(is_null($value)) {
-                $statement->bindValue($bindKey, $value, PDO::PARAM_NULL);
+                $statement->bindValue($prefix .$key, $value, PDO::PARAM_NULL);
             }
             else {
-                $statement->bindValue($bindKey, $value, PDO::PARAM_STR);
+                $statement->bindValue($prefix .$key, $value, PDO::PARAM_STR);
             }
         }
     }
```

Why I reverted it, after you?

**Comment by tomvlk** [comment]
@LuckyCyborg Please, you didn't write the current DBAL in Nova, it's exactly a copy of the Engine, changed.

**Comment by LuckyCyborg** [comment]
@tomvlk I don't said that I written alone this code, from **\Nova\Database**... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk I will say you, you so vainglorious, what will happen into bindParams, when used into **Connection::update** for example:

### First call

```php
        // Bind fields
        $this->bindParams($stmt, $data, $paramTypes, ':field_');
``'

will result into binding of 

```
$statement->bindValue(1, 'admin', PDO::PARAM_STR);
```

### Second call

```php
        // Bind values
        $this->bindParams($stmt, $bindParams, $paramTypes);
``'

will result into binding of 

```
$statement->bindValue(1, 1, PDO::PARAM_INT);
```

Result?

```sql

UPDATE user SET username=1 WHERE id=1"
```

## You see the light?

**Comment by LuckyCyborg** [comment]
@tomvlk Then, from reasons about incorrect calculation of numeric binding index, please revert that:

```diff
@@ -177,24 +177,29 @@ public function bindParams($statement, array $params, array $paramTypes = array(
 
         // Bind the key and values (only if given).
         foreach ($params as $key => $value) {
+            $bindKey = $prefix .$key;
+            if (is_int($key)) {
+                $bindKey = $key+1;
+            }
+
             if(isset($paramTypes[$key])) {
-                $statement->bindValue($prefix .$key, $value, $paramTypes[$key]);
+                $statement->bindValue($bindKey, $value, $paramTypes[$key]);
 
                 continue;
             }
 
             // No parameter Type found, we try our best of to guess it.
             if (is_integer($value)) {
-                $statement->bindValue($prefix .$key, $value, PDO::PARAM_INT);
+                $statement->bindValue($bindKey, $value, PDO::PARAM_INT);
             }
             else if (is_bool($value)) {
-                $statement->bindValue($prefix .$key, $value, PDO::PARAM_BOOL);
+                $statement->bindValue($bindKey, $value, PDO::PARAM_BOOL);
             }
             else if(is_null($value)) {
-                $statement->bindValue($prefix .$key, $value, PDO::PARAM_NULL);
+                $statement->bindValue($bindKey, $value, PDO::PARAM_NULL);
             }
             else {
-                $statement->bindValue($prefix .$key, $value, PDO::PARAM_STR);
+                $statement->bindValue($bindKey, $value, PDO::PARAM_STR);
             }
         }
     }
```

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, finally I commented out the sequence

```php
if (is_int($key)) {
    $bindKey = $key+1;
}
```

If we really want numeric index binding, we need to invent a better method to calculate it. 

An idea is to a **preg_match** into **PDOStatement::debugDumpParams** to find the existent parameters number.

**Comment by LuckyCyborg** [comment]
@tomvlk Then, maybe I have a pattern to extract the existent bindings number from PDOStatement::debugDumpParams ...

It is 
```
^Params:.\s(.+)$
```

Today I will try to make a method to return the actual number of parameters already bind into PDOStatement.

You are happy now? :smirk:

**Comment by tomvlk** [comment]
I'm starting to create it in a separate package. Then make a injector build in to nova to inject the connection. PDO plain, so no conflicts will occur.

**Comment by LuckyCyborg** [comment]
@tomvlk Plain PDO you have also into QueryBuilder. Why you not use it?

You can make it to fetch Classes too... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk Also, probably we can calculate the number of previous bind parameters, but how, after all, you will synchronize the **$paramTypes** with ?

If they aren't synchronized, as indexes, the Fail will be spectacular. :smile:

**Comment by LuckyCyborg** [comment]
@tomvlk Also, if you are going Package, you can use directly the **DBAL** Package, that Doctrine based. :smirk: 

Okay, now I go to eat, I will be back in one hour.

Take care! :+1:

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, I merged you latest PR, that with PHPDOC and fix into '\Exception'. :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, then, in principle we written and have now a function able to return the number of already bind parameters in a **PDOStatement**. And as principle, it works.

But, it is based, like I said, in a **preg_match_all** of  **PDOStatement::debugDumpParams** output.

That's not the fastest thing into World, to be honest. BUT, it is the single way to know from where we start the indexed binding.

Still we have the problem of parameter types array, which should be synchronized with the flow, otherwise resulting spectacular fails...

**Comment by tomvlk** [comment]
I'm currently working on a separate package, and going to make it Nova independent.
It could be in Nova, then I will add it to the composer, encapsulate the Entity class and let the PDO connection be injected into the ORM.

Now it's to all your guys and @daveismyname to decide if you wan't it included or not.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> I'm currently working on a separate package, and going to make it Nova independent.

I'm glad to know and I wish you: Good Luck! :+1: 

> It could be in Nova, then I will add it to the composer, encapsulate the Entity class and let the PDO connection be injected into the ORM.

Glad to know that we have a new option to choose! :+1: 

> Now it's to all your guys and @daveismyname to decide if you wan't it included or not.

That's will be seen... If it is really nice, why not? Still, us we are **Doctrine ORM** fans, then go figure! Yet, I don't know the Dave's likening into ORMs.

**Wait a second!** What will happen with **\Nova\ORM**, in your opinion? You abandoned it?

**Pull request merged**
