### PR TITLE
Renewing Demo with overview & better database demo.

### PR DESCRIPTION
**Pull request by tomvlk**
Adding a demo overview, better database demo.

Ready!

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, I renamed **superInsert** as **insertAll**, our Manager nitpicked that, sorry!

**Comment by tomvlk** [comment]
@LuckyCyborg Look at the last 2 commits, there were some errors in the code..

**Comment by LuckyCyborg** [comment]
@tomvlk Yours commits or my commits?

**Comment by tomvlk** [comment]
@LuckyCyborg 2c200f0 and 5a7c697 in this pull request. No big problems, it's fixed. But only after this pull is merged. And it isn't ready yet...

**Comment by LuckyCyborg** [comment]
@tomvlk Real failure is that:

```
return $this->insert($table, $data, $transaction, is_array($data[0]))
```

But I don't seen in patches they to touch there...

The **\PDO** can be explained on PHP version differences, maybe our base version, **5.6** under Slackware accept it. Also the Hostgator's 5.5 too. :smirk: 

To be sure, I will ask specially about the **\PDO** thing, after Santa Claus Day.

**Comment by tomvlk** [comment]
@LuckyCyborg It doesn't work without the \ on PDO for me.

**Comment by LuckyCyborg** [comment]
@tomvlk Then do it that way, to be all of ours safe! :smile: 

BTW, you develop platform details are... ?

**Comment by tomvlk** [comment]
@LuckyCyborg I'm currently on Windows, but also no Mac, I have the same issues for the \PDO stuff.
I always used \PDO instead of PDO. 
It could also be fixed with
```php
use \PDO;
```
on the top. But ye, it's only a \.

**Comment by LuckyCyborg** [comment]
@tomvlk I'm glad that you figured fast how to use our base Controllers, you adopted even our style, called by us **Cake Style**... :smile: 

If you ask about another one style, called by us **Lara Style** and presented there as **Laravel Style**, why exists, then it is very useful on Event **Listeners**.

Let's say that you have the **Homepage**, who contains a number of **Blocks**, generated dynamically by some Modules. We use an **Event** deployed in **beforeFlight** to collect an array of **View** instances, who represent the blocks and to render them on-site.

It is about a rule which we follow: **processing first, rendering seconds**.

**Comment by tomvlk** [comment]
@LuckyCyborg Ye, it costs me some time. 
I think that there should be a sort of demo with a sidebar menu or something, and use that with the laravel style. Maybe a good idea for making demo page for?

**Comment by LuckyCyborg** [comment]
@tomvlk If you want, I can prepare a Layout for this things, and to introduce some small changes as a Base Controller in **\App\Modules\Demo\Core\BaseController** who read a **Config** entry and pass the data to layout, who generate an nice menu, bootstrap style.

**Comment by tomvlk** [comment]
@LuckyCyborg Why not, would be good for our end users too to see a working demo with the menu that's dynamic. 
You can prepare it without touching the files in this pull right?

**Comment by LuckyCyborg** [comment]
Well, better to way your merge and then I will enter. But, after all, I have to work in another areas of the Module. I will start now, wait you to finish and I will end the integration...

**Comment by tomvlk** [comment]
@LuckyCyborg Im working on DBAL demos now, after that the demo's are done I think.

**Comment by LuckyCyborg** [comment]
@tomvlk Then, I will complete the infrastructure of Demo module, and add its Base Controller specialization, and the dedicated Layout.

I think that it is a good Idea, even as demonstration to understand the others how it works the flow **Controller -> View -> Layout**

**Comment by tomvlk** [comment]
**Ok, the basic demo, for understanding the main parts of the engine and dbal is done**

## Merge ready for me

**Pull request merged**
